/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.forme;

import com.classe.ConvertirChiffreEnLettre;
import com.classe.classe_avance;
import com.requete.Connecter_bd;
import com.requete.connections;
import com.requete.requet_avance;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import static java.lang.Integer.max;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author VONINAHITRA
 */
public class avance_add extends javax.swing.JFrame {
private String query;
private Connecter_bd con_db;
connections maCon = new connections();
ResultSet rs;
PreparedStatement ps;
Statement st;
Connection conc;
/////////////////////////////Configuration du mois//////////////////////////////

    /** Creates new form avance_add */
    public avance_add() {
        initComponents();
        this.setLocationRelativeTo(null);
        print_lettre_avance.setVisible(false);
    }
private void select_num_perso() throws Exception, SQLException{
    txt_num_perso_avcance.removeAllItems();
    con_db = new Connecter_bd();
    query = "select * from tab_perso";
    ResultSet rs = con_db.executeQuery(query);
    while(rs.next()){
       String perso = rs.getString("num_perso").toString();
       txt_num_perso_avcance.addItem(perso);
   } 
}
private void select_nom_perso() throws Exception, SQLException{
    con_db = new Connecter_bd();
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_avcance.getSelectedItem().toString();
    query = "select * from tab_perso where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String perso = rs.getString("nom_pre_perso").toString();
       String num = rs.getString("num_perso");
       txt_nom_perso_avance.setText(perso);
       txt_num_perso_contrat2.setText(num);
   } 
}
private void selct_ifos_perso() throws Exception{
    String num_p_contrat = txt_num_perso_avcance.getSelectedItem().toString();
   // txt_num_perso_avcance.removeAllItems();
    con_db = new Connecter_bd();
    query = "select * from tab_contrat where num_perso='"+num_p_contrat+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String sal_p_c = rs.getString("sal_base_contrat").toString();
       txt_sal_bas_avance.setText(sal_p_c);
       txt_sal_bas_avance.setForeground(Color.black);
       double total_sal = Double.parseDouble(sal_p_c);
       double divise = 2;
       double max = total_sal/divise;
       String final_max =Double.toString(max);
       txt_dispo_avance.setText(final_max);
       txt_num_perso_avcance.setSelectedItem(sal_p_c);
       txt_som_reti_avance.enable(true);
       select_nom_perso();
       
   } else{
        
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_sal_bas_avance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_num_perso_contrat2 = new javax.swing.JTextField();
        txt_nom_perso_avance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_annee_avance = new com.toedter.calendar.JYearChooser();
        jLabel9 = new javax.swing.JLabel();
        txt_pdu_avance = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txt_pau_avance = new com.toedter.calendar.JDateChooser();
        btn_ok_dt_avance = new javax.swing.JButton();
        txt_num_perso_avcance = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_mois_avance = new com.toedter.calendar.JMonthChooser();
        btn_enreg_avance = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txt_som_reti_avance = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_ok_sal_avance = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_reste_avance = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_netpay_avance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_dispo_avance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        print_lettre_avance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AVANCE SUR SALAIRE");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Donate_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Informations du personnel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txt_sal_bas_avance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sal_bas_avance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_sal_bas_avance.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Salaire de base :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Ar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nom te prénom :");

        txt_num_perso_contrat2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_num_perso_contrat2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_num_perso_contrat2.setEnabled(false);

        txt_nom_perso_avance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nom_perso_avance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_perso_avance.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("N° :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nom_perso_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_sal_bas_avance, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txt_num_perso_contrat2))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nom_perso_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_num_perso_contrat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_sal_bas_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Date d'avance sur salaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Mois du :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Année :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Période du");

        txt_pdu_avance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("au ");

        txt_pau_avance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_ok_dt_avance.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_dt_avance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_dt_avance.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_dt_avance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Approval_25px.png"))); // NOI18N
        btn_ok_dt_avance.setText("Approuver");
        btn_ok_dt_avance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_dt_avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_dt_avanceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("N° personnel :");

        txt_mois_avance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txt_annee_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(txt_mois_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ok_dt_avance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_pau_avance, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_num_perso_avcance, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pdu_avance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_num_perso_avcance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(txt_pdu_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pau_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mois_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_annee_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(btn_ok_dt_avance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_enreg_avance.setBackground(new java.awt.Color(0, 102, 153));
        btn_enreg_avance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enreg_avance.setForeground(new java.awt.Color(255, 255, 255));
        btn_enreg_avance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Checkmark_25px.png"))); // NOI18N
        btn_enreg_avance.setText("Enregistrer");
        btn_enreg_avance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enreg_avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enreg_avanceActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Close_Window_25px.png"))); // NOI18N
        jButton3.setText("Annuler/Fermer");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Reset_25px.png"))); // NOI18N
        jButton1.setText("Effacer");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Informations du personnel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Ar");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Somme à retirer :");

        btn_ok_sal_avance.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_sal_avance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_sal_avance.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_sal_avance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Ok_25px.png"))); // NOI18N
        btn_ok_sal_avance.setText("Valider");
        btn_ok_sal_avance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_sal_avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_sal_avanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_som_reti_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_ok_sal_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_som_reti_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ok_sal_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Informations du personnel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Reste du salaire:");

        txt_reste_avance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_reste_avance.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Ar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Net à payer :");

        txt_netpay_avance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_netpay_avance.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ar");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Avance  Disponible :");

        txt_dispo_avance.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_dispo_avance.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Ar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_netpay_avance)
                            .addComponent(txt_reste_avance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(108, 108, 108))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_dispo_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dispo_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_netpay_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_reste_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(print_lettre_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_enreg_avance, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(print_lettre_avance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_enreg_avance, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    txt_som_reti_avance.enable(false);
   // print_lettre_avance.setText("0.0");
        try {
        select_num_perso();
    } catch (Exception ex) {
        Logger.getLogger(avance_add.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void btn_ok_dt_avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_dt_avanceActionPerformed
     
///verifier si les chaps obligatoires sont vides
        if(((JTextField)txt_pdu_avance.getDateEditor().getUiComponent()).getText().equals("")==false || 
            ((JTextField)txt_pau_avance.getDateEditor().getUiComponent()).getText().equals("")==false){
             //le15dumois();
//Verifier si le jour de la date actuelle est supérieur ou equale à 15.
             LocalDate mois_ann_now = LocalDate.now();
             int an_now = mois_ann_now.getYear();
             LocalDateTime now = LocalDateTime.MAX.now();
         int day = now.getDayOfMonth();
         //ETO LE 15 EM DU MOIS
         int quinze = 15;
        if(day>=quinze){
           //pour l'annee
DateFormat dateFormat_an = new SimpleDateFormat("yyyy");
Date pdu = txt_pdu_avance.getDate();
String pdu2 = dateFormat_an.format(pdu);
Date pau = txt_pau_avance.getDate();
String pau2 = dateFormat_an.format(pau);
    int pan1_1 = Integer.parseInt(pdu2);
    int pan2_2 = Integer.parseInt(pau2);
          //pour le mois
DateFormat dateFormat_ms = new SimpleDateFormat("MM");
Date pdu_ms = txt_pdu_avance.getDate();
String pdu1_ms = dateFormat_ms.format(pdu_ms);
Date pau_ms = txt_pau_avance.getDate();
String pau2_ms = dateFormat_ms.format(pau_ms);
    int pdu_ms1 = Integer.parseInt(pdu1_ms);
    int pau_ms1 = Integer.parseInt(pau2_ms);
     if((pan1_1==pan2_2) && (pdu_ms1 == pau_ms1)){
Date date_now = new Date();
DateFormat dateFormat_now_an = new SimpleDateFormat("yyyy");
String dt_an_now = dateFormat_now_an.format(date_now);
DateFormat dateFormat_now_mw = new SimpleDateFormat("MM");
String dt_mw_now = dateFormat_now_mw.format(date_now);
    int an_now_1 = Integer.parseInt(dt_an_now);
    int mw_now_1 = Integer.parseInt(dt_mw_now);
int an = txt_annee_avance.getYear();
int mw = txt_mois_avance.getMonth();
int mws= mw+01;
    if((mw_now_1==pdu_ms1) && (an_now_1==pan1_1) && (an==an_now_1) && (mws==mw_now_1)){
    try {
        int annee = txt_annee_avance.getYear();
        //String an = Integer.toString(annee);
        String num_p = txt_num_perso_avcance.getSelectedItem().toString();
        //String ms = txt_mois_avance.getSelectedItem().toString();
        con_db = new Connecter_bd();
        query = "select * from tab_avance where num_perso='"+num_p+"' and mois_avance='"+mws+"' and annee_avance='"+annee+"'";
        ResultSet rs = con_db.executeQuery(query);
        if(rs.next()){
            JOptionPane.showMessageDialog(null,"Désolé vous ne pouvez pas prendre deux (02) fois d'une avance dans un mois, sauf la modification\n Veillez entendre le mois prochain SVP.","Message",JOptionPane.WARNING_MESSAGE);   
        }else{
        SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
        String dt1 = dt.format(txt_pdu_avance.getDate());
        String dt2 = dt.format(txt_pau_avance.getDate());
                Date date1 = dt.parse(dt1);
                Date date2 = dt.parse(dt2);
        if(date1.before(date2)){
         selct_ifos_perso() ;
        }else{
         JOptionPane.showMessageDialog(null,"Désolé! La date de débute du période doit être inférieur à la date de fin du période, SVP","Message",JOptionPane.WARNING_MESSAGE);         
        }
            
        }
    } catch (Exception ex) {
        Logger.getLogger(avance_add.class.getName()).log(Level.SEVERE, null, ex);
    }
    }else{
             JOptionPane.showMessageDialog(null,"Désolé! Le mois ou l'année doivent être actuelle","Message",JOptionPane.WARNING_MESSAGE);   
    }
     }else{
            JOptionPane.showMessageDialog(null,"Désolé! Le mois et l'année de ce deux dates doivent être éguals","Message",JOptionPane.WARNING_MESSAGE);  
     } 
       
        }else{
            JOptionPane.showMessageDialog(null,"Désolé! Vous devez entendre le 15eme du mois\n pour pouvoir effectué l'avance de votre salaire SVP","Message",JOptionPane.WARNING_MESSAGE);   
         }
        }else{
            JOptionPane.showMessageDialog(null,"Veillez remplir les deux champs de la date,SVP!","Message",JOptionPane.WARNING_MESSAGE);
        }    
        
  
    }//GEN-LAST:event_btn_ok_dt_avanceActionPerformed
 
    private void le15dumois() throws Exception{
    //String

/*DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
String date_now = dateFormat.format(actuelle.get);
    int an_actuelle = date_now.getYear();
    int mw_actuelle = */

   //  String ;
        // txt_num_perso_avcance.removeAllItems();
        LocalDate mois_ann_now = LocalDate.now();
        int an_now = mois_ann_now.getYear();
        // Month mois_now = mois_ann_now.getMonth();
        LocalDateTime now = LocalDateTime.MAX.now();
        int day = now.getDayOfMonth();
         int quinze = 15;
        String day_s = Integer.toString(day);
        if(day<quinze){
        JOptionPane.showMessageDialog(null,"Désolé! Vous devez entendre le 15eme du mois\n pour  effectuer une avance de votre salaire","Message",JOptionPane.WARNING_MESSAGE);
        }else { 
    int annee = txt_annee_avance.getYear();
    //String an = Integer.toString(annee);
    String num_p = txt_num_perso_avcance.getSelectedItem().toString();
    //String ms = txt_mois_avance.getSelectedItem().toString();
    int ms = txt_mois_avance.getMonth();
    con_db = new Connecter_bd();
    query = "select * from tab_avance where num_perso='"+num_p+"' and mois_avance='"+ms+"' and annee_avance='"+annee+"'";
    ResultSet rs = con_db.executeQuery(query);
         if(rs.next()){
        JOptionPane.showMessageDialog(null,"Désolé Vous ne pouvez pas prendre deux (02) fois d'avance\n Veillez entendre le mois prochaine","Message",JOptionPane.WARNING_MESSAGE);         
        }else{
        selct_ifos_perso();
        }
           //select_num_perso();
          // select_nom_perso();
         // selct_ifos_perso();
        }
    }
    public void verifier_date_avance() throws Exception{
    con_db = new Connecter_bd();
   // String num_perso = txt_num_perso_avcance.getSelectedItem().toString();  and num_perso='"+num_perso+"'
   // query = "select * from tab_avance where mois_avance='"+mois+"' and  annee_avance='"+annee+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
        JOptionPane.showMessageDialog(null,"Existe dejà","Message",JOptionPane.WARNING_MESSAGE);
    }else{
       JOptionPane.showMessageDialog(null,"Pas encore","Message",JOptionPane.WARNING_MESSAGE); 
    }
// txt_mois_avance.getS;
     
    //String dt_mois_avance = txt_mois_avance.get
    //query = "select * from tab_avance where mois_avance='"++"'";
    }
    private void btn_ok_sal_avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_sal_avanceActionPerformed
      /*test
          Calendar calendrier = Calendar.getInstance();
          int max = calendrier.getActualMaximum(Calendar.DAY_OF_MONTH);
          int actuel = calendrier.get(Calendar.DAY_OF_MONTH);
          String ok_max = Integer.toString(max);
          int o = 16;
          String sz = Integer.toString(o);
          int somme= max-o; 
          String total = Integer.toString(somme);
          txt_num_avance.setText(total);
    */
      /*Calendar calendrier = Calendar.getInstance();
      int max_jrs = calendrier.getActualMinimum(Calendar.DAY_OF_MONTH);
      int mois_actuel = calendrier.get(Calendar.DAY_OF_MONTH);
      int quinze = 15;
      int seize =16;
      int treize =13;
      int quatorze = 14;
      int comparaison = 15;
      //convetisation en type string
      String max_jrs_s = Integer.toString(max_jrs);
      String mois_actuel_s = Integer.toString(mois_actuel);
      String quize_s = Integer.toString(quinze);
      String seize_s = Integer.toString(seize);
      String treize_s = Integer.toString(treize);
      String quatorze_s = Integer.toString(quatorze);
      /*tena mety bee 
      LocalDateTime now = LocalDateTime.MAX.now();
        int day = now.getDayOfMonth();
        String day_s = Integer.toString(day);
     if(day>=quinze){
         txt_num_avance.setText(day_s);
     }else{
         txt_num_avance.setText("Mbola ts mahazo vola ianao");
     }*/
        
      //autres fonctions
 
      String sal_retir = txt_som_reti_avance.getText();
      
      if(sal_retir.equals("")==true){
      JOptionPane.showMessageDialog(null,"Veillez completer les champs ou format correcte \n Veillez remplire, SVP","Message",JOptionPane.WARNING_MESSAGE);     
      }else{
      double sal_retir_final = Double.parseDouble(sal_retir);
      String dispo_max = txt_dispo_avance.getText();
      double dispo_max_final = Double.parseDouble(dispo_max);
      if(sal_retir_final>dispo_max_final){
          JOptionPane.showMessageDialog(null,"Désole Vous ne pouvez pas rétirer plus de 50% de votre salaire de base","Message",JOptionPane.WARNING_MESSAGE);
      }else{
      String lettrer = print_lettre_avance.getText();
      double avance = Double.parseDouble(txt_som_reti_avance.getText());
      ConvertirChiffreEnLettre c = new ConvertirChiffreEnLettre();
        String n[] = (avance+"").split("\\.");
        long entier = Long.parseLong(n[0]);
        long decimal=Long.parseLong(n[1]);
        String lettret = (decimal > 0) ? c.convert(entier) + " virgule " + c.convert(decimal) : c.convert(entier);
        //System.out.println(num + " : " + lettre + " Ariary");
      print_lettre_avance.setText(lettret+ " " + lettrer + " Ariary");
      String sal_base = txt_sal_bas_avance.getText();
      Double sal_base_c = Double.parseDouble(sal_base);
      Double somme_reste = sal_base_c - sal_retir_final;
      String somme_rest_final = Double.toString(somme_reste);
      txt_reste_avance.setText(somme_rest_final);
      txt_netpay_avance.setText(sal_retir);
      
      }}
    }//GEN-LAST:event_btn_ok_sal_avanceActionPerformed
 /*private boolean  acceptchiffre(){
        boolean num = true;
        num=  txt_som_reti_avance.getText().matches("^[0-9]");
        return num;
    }*/
    private void btn_enreg_avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enreg_avanceActionPerformed
    int infos = JOptionPane.showConfirmDialog(this,"Voullez-vous vraiment effectué cette opération ?","Message",JOptionPane.YES_NO_OPTION);
            if(infos==JOptionPane.YES_OPTION){  
             if(txt_reste_avance.getText().equals("")==true){
                 JOptionPane.showMessageDialog(null,"Veillez entrer la somme que Vous voullez rétirer","Message",JOptionPane.WARNING_MESSAGE);
             }else{
String num_p_av = txt_num_perso_avcance.getSelectedItem().toString();
String netpay_av = txt_netpay_avance.getText();
Double netp = Double.parseDouble(netpay_av);
//LocalDate dt_now = LocalDate.now();
Date actuelle = new Date();
DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
String date_now = dateFormat.format(actuelle);
int an = txt_annee_avance.getYear();
String annee = Integer.toString(an);
String reste_av = txt_reste_avance.getText();
//String mois = txt_mois_avance.getSelectedItem().toString();
int mw = txt_mois_avance.getMonth();
int mois1 = mw+01;
String mois = Integer.toString(mois1);
Double reste = Double.parseDouble(reste_av);
SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
String dtdu = dt.format(txt_pdu_avance.getDate());
String dtau = dt.format(txt_pau_avance.getDate());
String nom_pre_avance = txt_nom_perso_avance.getText();
String enlettre = print_lettre_avance.getText();
classe_avance cla  = new classe_avance(num_p_av,nom_pre_avance, netp,date_now,mois,annee,dtdu,dtau,reste,enlettre);
        requet_avance rqta = new requet_avance();
    try {
        rqta.ajouter(cla);
        JOptionPane.showMessageDialog(null,"Les informations ont été  bien enregistrées ","Message",JOptionPane.PLAIN_MESSAGE);  
    } catch (Exception ex) {
        Logger.getLogger(avance_add.class.getName()).log(Level.SEVERE, null, ex);
    }}
    }//GEN-LAST:event_btn_enreg_avanceActionPerformed
else{
            }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       effacer_avance_add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
private void effacer_avance_add(){
  txt_nom_perso_avance.setText("");
  txt_num_perso_contrat2.setText("");
  txt_sal_bas_avance.setText("");
  txt_som_reti_avance.setText("");
  txt_dispo_avance.setText("");
  txt_netpay_avance.setText("");
  txt_reste_avance.setText("");
  txt_pdu_avance.setDate(null);
  txt_pau_avance.setDate(null);
}
    
private void  ok_mois_annee(){
    
    Date actuelle = new Date();
    DateFormat dateFormat = new SimpleDateFormat("MM");
    String date_now = dateFormat.format(actuelle);
   // txt_mw.setText(date_now);   
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(avance_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(avance_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(avance_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(avance_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new avance_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enreg_avance;
    private javax.swing.JButton btn_ok_dt_avance;
    private javax.swing.JButton btn_ok_sal_avance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField print_lettre_avance;
    private com.toedter.calendar.JYearChooser txt_annee_avance;
    private javax.swing.JTextField txt_dispo_avance;
    private com.toedter.calendar.JMonthChooser txt_mois_avance;
    private javax.swing.JTextField txt_netpay_avance;
    private javax.swing.JTextField txt_nom_perso_avance;
    private javax.swing.JComboBox<String> txt_num_perso_avcance;
    private javax.swing.JTextField txt_num_perso_contrat2;
    private com.toedter.calendar.JDateChooser txt_pau_avance;
    private com.toedter.calendar.JDateChooser txt_pdu_avance;
    private javax.swing.JTextField txt_reste_avance;
    private javax.swing.JTextField txt_sal_bas_avance;
    private javax.swing.JTextField txt_som_reti_avance;
    // End of variables declaration//GEN-END:variables

}
