/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forme;

import com.classe.DeuxChiffresApresVirgule;
import com.classe.histogramme;
import com.requete.Connecter_bd;
import com.requete.connections;
import com.requete.requet_impression;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author VONIANAHITRA
 */
public class globale_salaire extends javax.swing.JFrame {

    
   PreparedStatement ps;
    PreparedStatement pse;
    Statement st;
    Statement ste;
    Connection conc;
    Connecter_bd con_db = new Connecter_bd();
    connections maCon = new connections();
    String query;
    ResultSet rs;

////////////////////////////////personnel///////////////////////////////////////
    public DefaultTableModel tab_osief1er;
    private String num_perso;
    private String num_perso2;
    private String sexe_perso;
    private String dt_perso;
    private String situ_perso;
    private String nb_enf_perso;
    private String adrs_perso ;
    private String tel_perso; 
    public int mois;
     /* Creates new form declaration
     */
    //pour Cnaps
    public DefaultTableModel tab_cnaps;
        //Pour le salaire globale
//pour en une année
public  DefaultTableModel tab_globale;
private String num;
private String somme_base;
private String somme_brute;
//pour en un mois

//pour l'irsa
public  DefaultTableModel tabirsa;
private String numirsa;
private String nomirsa;
private String sommeirsa;
//pour le cnaps
public  DefaultTableModel tabcnaps;
private String numcnaps;
private String nomcnaps;
private String sommcnaps;
//pour le osief
public  DefaultTableModel tabosief;
private String numosief;
private String nomosief;
private String sommeosief;
ResultSet rse;
//pour le salaire globale par classification.
//pour en une année
public  DefaultTableModel tab_globale_classifi;
private String num_clasifi;
private String nom_clasifi;
private String somme_clasifi;
    /**
     * Creates new form declaration_all
     */
    public globale_salaire() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_salaire_globale_all = new javax.swing.JTable();
        txt_somme_globale = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_annee_chercher = new com.toedter.calendar.JYearChooser();
        btn_afficher_sal_base_annee = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btn_histo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_salaire_globale_all_clasifi = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txt_annee_clasifi = new com.toedter.calendar.JYearChooser();
        btn_annee_clasifi = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        txt_total_clasifi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_accueil = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        table_salaire_globale_all.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_salaire_globale_all.setRowHeight(25);
        jScrollPane1.setViewportView(table_salaire_globale_all);

        txt_somme_globale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_somme_globale.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_somme_globale.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Total :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("AR");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("En une année");

        btn_afficher_sal_base_annee.setBackground(new java.awt.Color(0, 102, 153));
        btn_afficher_sal_base_annee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_afficher_sal_base_annee.setForeground(new java.awt.Color(255, 255, 255));
        btn_afficher_sal_base_annee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Search_25px_1.png"))); // NOI18N
        btn_afficher_sal_base_annee.setText("Afficher");
        btn_afficher_sal_base_annee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_afficher_sal_base_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afficher_sal_base_anneeActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 102, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Print_25px.png"))); // NOI18N
        jButton11.setText("Imprimer");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btn_histo.setBackground(new java.awt.Color(0, 102, 153));
        btn_histo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_histo.setForeground(new java.awt.Color(255, 255, 255));
        btn_histo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_account_25px.png"))); // NOI18N
        btn_histo.setText("Histogramme");
        btn_histo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_histo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_histoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_somme_globale, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txt_annee_chercher, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_afficher_sal_base_annee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_histo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_somme_globale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_annee_chercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_afficher_sal_base_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_histo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("SALAIRE GLOBAL", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        table_salaire_globale_all_clasifi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_salaire_globale_all_clasifi.setRowHeight(25);
        jScrollPane5.setViewportView(table_salaire_globale_all_clasifi);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("AR");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setText("En une année");

        btn_annee_clasifi.setBackground(new java.awt.Color(0, 102, 153));
        btn_annee_clasifi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_annee_clasifi.setForeground(new java.awt.Color(255, 255, 255));
        btn_annee_clasifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Search_25px_1.png"))); // NOI18N
        btn_annee_clasifi.setText("Afficher");
        btn_annee_clasifi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_annee_clasifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annee_clasifiActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(0, 102, 153));
        jButton34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Print_25px.png"))); // NOI18N
        jButton34.setText("Imprimer");
        jButton34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton34.setMaximumSize(new java.awt.Dimension(103, 33));
        jButton34.setMinimumSize(new java.awt.Dimension(103, 33));
        jButton34.setPreferredSize(new java.awt.Dimension(103, 33));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        txt_total_clasifi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_total_clasifi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_total_clasifi.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_clasifi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btn_annee_clasifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_annee_clasifi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel48)))
                        .addGap(205, 205, 205))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_total_clasifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(18, 18, 18)
                        .addComponent(txt_annee_clasifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_annee_clasifi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SALAIRE GLOBAL PAR CLASSIFICATION", jPanel8);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        menu_accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Home_20px.png"))); // NOI18N
        menu_accueil.setText("Menu principale");
        menu_accueil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu_accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_accueilMouseClicked(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Return_25px.png"))); // NOI18N
        jMenuItem1.setText("Accueil principale");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_accueil.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Sales_Performance_25px.png"))); // NOI18N
        jMenuItem3.setText("Déclarations");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_accueil.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon_48/icons8_Open_25px_1.png"))); // NOI18N
        jMenuItem4.setText("Activités");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_accueil.add(jMenuItem4);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Logout_Rounded_Left_25px.png"))); // NOI18N
        jMenuItem2.setText("Déconnexion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_accueil.add(jMenuItem2);

        jMenuBar1.add(menu_accueil);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_afficher_sal_base_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afficher_sal_base_anneeActionPerformed
        txt_somme_globale.setText("0.0");
        try {
            config_tab_annee();
            //compteperso_vola_annee();
            // compteperso_vola();
        } catch (Exception ex) {
            Logger.getLogger(salaire_globale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_afficher_sal_base_anneeActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/payement","root","");
            final String  JRXML = "C:\\Users\\VONIANAHITRA\\Documents\\NetBeansProjects\\Gestion_paie\\src\\impression\\globale.jrxml";
            // String sql = "select * from print_bulletin where matricule like '%"+num+"%'";
            Map param = new HashMap();
            param.put("ANNEE_GLOBALE",txt_annee_chercher.getYear());
            //param.put("DATE_AVANCE",txt_dt_imprimer_avance.getText());
            requet_impression print = new requet_impression();
            print.displayReport(JRXML, param, con);
            // config_tab_annee();
        } catch (Exception ex) {
            Logger.getLogger(declaration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_annee_clasifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annee_clasifiActionPerformed
        try {
            config_tab_annee_classifi();
            compteperso_vola_clasifi();
        } catch (Exception ex) {
            Logger.getLogger(salaire_globale.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_annee_clasifiActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/payement","root","");
            final String  JRXML = "C:\\Users\\VONIANAHITRA\\Documents\\NetBeansProjects\\Gestion_paie\\src\\impression\\globale_clasifi.jrxml";
            // String sql = "select * from print_bulletin where matricule like '%"+num+"%'";
            Map param = new HashMap();
            param.put("ANNEE_CLASIFI",txt_annee_clasifi.getYear());
            //param.put("DATE_AVANCE",txt_dt_imprimer_avance.getText());
            requet_impression print = new requet_impression();
            print.displayReport(JRXML, param, con);
            // config_tab_annee();
        } catch (Exception ex) {
            Logger.getLogger(declaration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        accueil_principale acp = new accueil_principale();
        acp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       declaration sal_g = new declaration();
        sal_g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        authentificaiton auth = new authentificaiton();
        auth.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menu_accueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_accueilMouseClicked

    }//GEN-LAST:event_menu_accueilMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
           config_tab_annee_standar() ;
           config_tab_annee_classifi_satand();
       } catch (Exception ex) {
           Logger.getLogger(globale_salaire.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        perso_entrep_contrat_avance_forme act = new perso_entrep_contrat_avance_forme();
        act.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btn_histoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_histoActionPerformed
       try {
           histogramme hist = new histogramme();
           int ann = txt_annee_chercher.getYear();
           hist.salaire_brut(ann);
       } catch (SQLException ex) {
           Logger.getLogger(globale_salaire.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_histoActionPerformed
public void config_tab_annee_standar() throws Exception{
        tab_globale = new DefaultTableModel();
//        tab_globale.addColumn("Année");
        tab_globale.addColumn("Matricule");
//        tab_globale.addColumn("Nom et prénom");
        tab_globale.addColumn("Classification du personnel");
       // tab_globale.addColumn("Somme du salaire net par mois");
        tab_globale.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
        table_salaire_globale_all.setModel(tab_globale);
     
        table_salaire_globale_all.getColumnModel().getColumn(0).setPreferredWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMaxWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMinWidth(200);
        
        table_salaire_globale_all.getColumnModel().getColumn(1).setPreferredWidth(300);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMaxWidth(300);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMinWidth(300);
      
        table_salaire_globale_all.getColumnModel().getColumn(2).setPreferredWidth(500);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMaxWidth(500);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMinWidth(500);
//        
//        table_salaire_globale_all.getColumnModel().getColumn(3).setPreferredWidth(300);
//        table_salaire_globale_all.getColumnModel().getColumn(3).setMaxWidth(300);
//        table_salaire_globale_all.getColumnModel().getColumn(3).setMinWidth(300);
      
       /* table_salaire_globale_all.getColumnModel().getColumn(3).setPreferredWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMaxWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMinWidth(400);*/
     
//      recuperer_val_anne();
 }
    
    public void config_tab_annee() throws Exception{
        tab_globale = new DefaultTableModel();
//        tab_globale.addColumn("Année");
        tab_globale.addColumn("Matricule");
//        tab_globale.addColumn("Nom et prénom");
        tab_globale.addColumn("Classification du personnel");
       // tab_globale.addColumn("Somme du salaire net par mois");
        tab_globale.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
        table_salaire_globale_all.setModel(tab_globale);
     
        table_salaire_globale_all.getColumnModel().getColumn(0).setPreferredWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMaxWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMinWidth(200);
        
        table_salaire_globale_all.getColumnModel().getColumn(1).setPreferredWidth(300);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMaxWidth(300);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMinWidth(300);
      
        table_salaire_globale_all.getColumnModel().getColumn(2).setPreferredWidth(500);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMaxWidth(500);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMinWidth(500);
//        
//        table_salaire_globale_all.getColumnModel().getColumn(3).setPreferredWidth(300);
//        table_salaire_globale_all.getColumnModel().getColumn(3).setMaxWidth(300);
//        table_salaire_globale_all.getColumnModel().getColumn(3).setMinWidth(300);
      
       /* table_salaire_globale_all.getColumnModel().getColumn(3).setPreferredWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMaxWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMinWidth(400);*/
     
      recuperer_val_anne();
 }
public void recuperer_val_anne() throws Exception{ 
        tab_globale.setRowCount(0);//initialisation du table
        int annee = txt_annee_chercher.getYear();
        query = "select tab_contrat.num_perso, tab_contrat.clasifi_contrat, sum(tab_paie.totale_av_bulletin) as salaire_annee,( select sum(tab_paie.totale_av_bulletin) as salaire from tab_paie where annee_bulletin='"+annee+"' group by tab_paie.annee_bulletin) as somme from tab_paie inner join tab_contrat on tab_contrat.num_perso = tab_paie.num_perso where tab_paie.annee_bulletin='"+annee+"' group by tab_paie.num_perso";
        //query = "select num_perso,sum(totale_av_bulletin) as salaire_annee from tab_paie where annee_bulletin='"+annee+"' group by num_perso ";
        st = maCon.Obtenirconnexion().createStatement();
        ResultSet rs = st.executeQuery(query);
while(rs.next()){
      num = rs.getString("num_perso");
      String clasifi = rs.getString("clasifi_contrat");
     // String nom = rs.getString("nom");
      somme_brute = rs.getString("salaire_annee");
      String somme =rs.getString("somme");
      txt_somme_globale.setText(somme);
      Object[] anneeobj = {num,clasifi, somme_brute};
      tab_globale.addRow(anneeobj);
    }

    } 
  public void config_tab_standard_globale() throws Exception{
        tab_globale = new DefaultTableModel();
        tab_globale.addColumn("Numéro");
       // tab_globale.addColumn("Nom et prénom");
        tab_globale.addColumn("Classification du personnel");
        tab_globale.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
       table_salaire_globale_all.setModel(tab_globale);
     
        table_salaire_globale_all.getColumnModel().getColumn(0).setPreferredWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMaxWidth(200);
        table_salaire_globale_all.getColumnModel().getColumn(0).setMinWidth(200);
        
        table_salaire_globale_all.getColumnModel().getColumn(1).setPreferredWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMaxWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(1).setMinWidth(400);
      
        table_salaire_globale_all.getColumnModel().getColumn(2).setPreferredWidth(600);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMaxWidth(600);
        table_salaire_globale_all.getColumnModel().getColumn(2).setMinWidth(600);
      
        /*table_salaire_globale_all.getColumnModel().getColumn(3).setPreferredWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMaxWidth(400);
        table_salaire_globale_all.getColumnModel().getColumn(3).setMinWidth(400);*/
     //recuperer_val_anne();
 }

 //pour la recherche en une année par classification
 public void   config_tab_standard_globale_classifi() throws Exception{
        tab_globale_classifi = new DefaultTableModel();
        tab_globale_classifi.addColumn("Classification du personnel");
        tab_globale_classifi.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all_clasifi.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
      table_salaire_globale_all_clasifi.setModel(tab_globale_classifi);
     
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setPreferredWidth(300);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMaxWidth(300);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMinWidth(300);
      
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setPreferredWidth(700);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMaxWidth(700);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMinWidth(700);
     
    // recuperer_val_anne_classifi();
 }

private void compteperso_vola_clasifi() throws SQLException {
//       String clasifi = txt_clasifi.getSelectedItem().toString();
       int annee = txt_annee_clasifi.getYear();
//       query = "select tab_contrat.num_perso, tab_contrat.clasifi_contrat, sum(tab_paie.totale_av_bulletin) as salaire_annee "
//                 + "from tab_paie inner join tab_contrat on tab_contrat.num_perso = tab_paie.num_perso where tab_paie.annee_bulletin='"+annee+"'"
//                 + " and  tab_contrat.clasifi_contrat='"+clasifi+"' group by clasifi_contrat";
       st = maCon.Obtenirconnexion().createStatement();
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            //String somme = rs.getString("salaire_annee");
            //txt_nbr_perso.setText(somme);
           // txt_total_clasifi.setText(somme);
        } else {

        }
    }
private void compteperso_vola_annee() throws SQLException {
      int annee = txt_annee_chercher.getYear();
      query = "select sum(tab_paie.totale_av_bulletin) as salaire from tab_paie where annee_bulletin='"+annee+"'";
        st = maCon.Obtenirconnexion().createStatement();
        ResultSet rs = st.executeQuery(query);
        if (rs.next()) {
            String somme = rs.getString("salaire");
            //txt_nbr_perso.setText(somme);
            double drala = Double.parseDouble(somme);
            String bob = DeuxChiffresApresVirgule.ChiffresApresVirgule(drala);
            txt_somme_globale.setText(bob);
        } else {

        }
    }
 

  
 public void total_calsifi(){
   
 }
 public void config_tab_annee_classifi_satand() throws Exception{
        tab_globale_classifi= new DefaultTableModel();
        tab_globale_classifi.addColumn("Classification du personnel");
        tab_globale_classifi.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all_clasifi.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
      table_salaire_globale_all_clasifi.setModel(tab_globale_classifi);
     
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setPreferredWidth(450);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMaxWidth(450);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMinWidth(450);
      
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setPreferredWidth(800);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMaxWidth(800);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMinWidth(800);
      
//     recuperer_val_anne_classifi();
 }
   public void config_tab_annee_classifi() throws Exception{
        tab_globale_classifi= new DefaultTableModel();
        tab_globale_classifi.addColumn("Classification du personnel");
        tab_globale_classifi.addColumn("Somme du salaire brute");
        JTableHeader tb = table_salaire_globale_all_clasifi.getTableHeader();
        tb.setBackground(new Color(0,102,153));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
      table_salaire_globale_all_clasifi.setModel(tab_globale_classifi);
     
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setPreferredWidth(450);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMaxWidth(450);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(0).setMinWidth(450);
      
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setPreferredWidth(800);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMaxWidth(800);
      table_salaire_globale_all_clasifi.getColumnModel().getColumn(1).setMinWidth(800);
      
     recuperer_val_anne_classifi();
 }
public void recuperer_val_anne_classifi() throws Exception{ 
        tab_globale_classifi.setRowCount(0);//initialisation du table
        int annee = txt_annee_chercher.getYear();
       // String clasifi = txt_clasifi.getSelectedItem().toString();
//         query = "select tab_contrat.num_perso, tab_contrat.clasifi_contrat, sum(tab_paie.totale_av_bulletin) as salaire_annee "
//                 + "from tab_paie inner join tab_contrat on tab_contrat.num_perso = tab_paie.num_perso where tab_paie.annee_bulletin='"+annee+"'"
//                 + " and  tab_contrat.clasifi_contrat='"+clasifi+"' group by num_perso";
//       // query = "select num_perso,sum(totale_av_bulletin) as salaire_annee from tab_paie where annee_bulletin='"+annee+"' group by num_perso ";
        query = "select tab_contrat.clasifi_contrat, sum(tab_paie.totale_av_bulletin) as salaire_annee,( select sum(tab_paie.totale_av_bulletin) as salaire from tab_paie where annee_bulletin='"+annee+"' group by tab_paie.annee_bulletin) as somme from tab_paie inner join tab_contrat on tab_contrat.num_perso = tab_paie.num_perso where tab_paie.annee_bulletin='"+annee+"' group by tab_contrat.clasifi_contrat";
        st = maCon.Obtenirconnexion().createStatement();
        ResultSet rs = st.executeQuery(query);
while(rs.next()){
     // num = rs.getString("num_perso");
      somme_base = rs.getString("clasifi_contrat");
      somme_brute = rs.getString("salaire_annee");
      String somme =rs.getString("somme");
      txt_total_clasifi.setText(somme);
      Object[] anneeobj = {somme_base, somme_brute};
      tab_globale_classifi.addRow(anneeobj);  
    }

    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(globale_salaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(globale_salaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(globale_salaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(globale_salaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new globale_salaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_afficher_sal_base_annee;
    private javax.swing.JButton btn_annee_clasifi;
    private javax.swing.JButton btn_histo;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton34;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menu_accueil;
    private javax.swing.JTable table_salaire_globale_all;
    private javax.swing.JTable table_salaire_globale_all_clasifi;
    private com.toedter.calendar.JYearChooser txt_annee_chercher;
    private com.toedter.calendar.JYearChooser txt_annee_clasifi;
    private javax.swing.JTextField txt_somme_globale;
    private javax.swing.JTextField txt_total_clasifi;
    // End of variables declaration//GEN-END:variables
}
