/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forme;

import com.classe.classe_osief;
import com.classe.classe_reduction;
import com.requete.Connecter_bd;
import com.requete.connections;
import com.requete.requet_osief;
import com.requete.requet_reduction;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author VONINAHITRA
 */
public class reduction_mod extends javax.swing.JFrame {
private String query;
private Connecter_bd con_db;
connections maCon = new connections();
ResultSet rs;
PreparedStatement ps;
Statement st;
Connection conc;
    /**
     * Creates new form NewJFrame
     */
    public reduction_mod() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txt_ref_mod_reduc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_annuler_entrep_mod = new javax.swing.JButton();
        btn_efacer_reduc_mod = new javax.swing.JButton();
        btn_enre_reduc_mod = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_annee_reduc_mod = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        txt_pdu_reduc_mod = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_pau_reduc_mod = new com.toedter.calendar.JDateChooser();
        btn_ok_dt_reduc_mod = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_mois_reduc_mod = new com.toedter.calendar.JMonthChooser();
        txt_num_perso_reduc_mod = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_nom_perso_reduc_mod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_num_perso_reduc2_mod = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_sal_base_reduc_mod = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_famille_reduc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_cession_sal_reduc_mod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nouri_loge_reduc_mod = new javax.swing.JTextField();
        txt_autres_reduc_mod = new javax.swing.JTextField();
        txt_vaca_sup = new javax.swing.JLabel();
        btn_ok_reduc_final_mod = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txt_totale_reduc_mod = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_irsa_reduc_mod = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_osief_reduc_mod = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_cnaps_reduc_mod = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_avances_reduc_mod = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_brute_av_reduc_mod = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_ref_mod_reduc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICATION DE LA REDUCTION ET TAXES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Tax_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_annuler_entrep_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_annuler_entrep_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_annuler_entrep_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_annuler_entrep_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Close_Window_25px.png"))); // NOI18N
        btn_annuler_entrep_mod.setText("Annuler/Fermer");
        btn_annuler_entrep_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_annuler_entrep_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annuler_entrep_modActionPerformed(evt);
            }
        });

        btn_efacer_reduc_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_efacer_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_efacer_reduc_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_efacer_reduc_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Reset_20px.png"))); // NOI18N
        btn_efacer_reduc_mod.setText("Effacer");
        btn_efacer_reduc_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_enre_reduc_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_enre_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enre_reduc_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_enre_reduc_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Checkmark_25px.png"))); // NOI18N
        btn_enre_reduc_mod.setText("Enregister");
        btn_enre_reduc_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enre_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enre_reduc_modActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Date d'avance sur salaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mois du :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Année :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Période du");

        txt_pdu_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("au ");

        txt_pau_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_ok_dt_reduc_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_dt_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_dt_reduc_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_dt_reduc_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Approval_25px.png"))); // NOI18N
        btn_ok_dt_reduc_mod.setText("Approuver");
        btn_ok_dt_reduc_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_dt_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_dt_reduc_modActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("N° personnel :");

        txt_mois_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_num_perso_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_num_perso_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_num_perso_reduc_mod.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txt_annee_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(txt_mois_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_num_perso_reduc_mod)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ok_dt_reduc_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txt_pau_reduc_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pdu_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel11)
                        .addComponent(txt_num_perso_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_pdu_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pau_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_mois_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_annee_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok_dt_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Date d'avance sur salaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txt_nom_perso_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nom_perso_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_perso_reduc_mod.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Nom te prénom :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("N° :");

        txt_num_perso_reduc2_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_num_perso_reduc2_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_num_perso_reduc2_mod.setEnabled(false);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Salaire de base :");

        txt_sal_base_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sal_base_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_sal_base_reduc_mod.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Ar");

        txt_famille_reduc.setEditable(false);
        txt_famille_reduc.setBackground(new java.awt.Color(255, 255, 255));
        txt_famille_reduc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_famille_reduc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_famille_reduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_famille_reducActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Allocation familliale :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Ar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel29))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nom_perso_reduc_mod)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_sal_base_reduc_mod, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_num_perso_reduc2_mod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(70, 70, 70)
                                .addComponent(txt_famille_reduc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_nom_perso_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_num_perso_reduc2_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sal_base_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_famille_reduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel6))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Date d'avance sur salaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cession de salaires :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nouriture et logement :");

        txt_nouri_loge_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nouri_loge_reduc_modActionPerformed(evt);
            }
        });

        txt_vaca_sup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_vaca_sup.setText("Autres réduction:");

        btn_ok_reduc_final_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_reduc_final_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_reduc_final_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_reduc_final_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Ok_25px.png"))); // NOI18N
        btn_ok_reduc_final_mod.setText("Valider");
        btn_ok_reduc_final_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_reduc_final_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_reduc_final_modActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Ar");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Ar");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Ar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_vaca_sup))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cession_sal_reduc_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(txt_nouri_loge_reduc_mod)
                    .addComponent(txt_autres_reduc_mod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ok_reduc_final_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cession_sal_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nouri_loge_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autres_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txt_vaca_sup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ok_reduc_final_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Date d'avance sur salaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Totale de réduction et taxes :");

        txt_totale_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_totale_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_totale_reduc_mod.setEnabled(false);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Ar");

        txt_irsa_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_irsa_reduc_mod.setEnabled(false);
        txt_irsa_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_irsa_reduc_modActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Ar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("IRSA:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("OSIEF :");

        txt_osief_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_osief_reduc_mod.setEnabled(false);
        txt_osief_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_osief_reduc_modActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Ar");

        txt_cnaps_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_cnaps_reduc_mod.setEnabled(false);
        txt_cnaps_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnaps_reduc_modActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Ar");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("CNaPS :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Avances :");

        txt_avances_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_avances_reduc_mod.setEnabled(false);
        txt_avances_reduc_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avances_reduc_modActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Ar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Salaire brute supléméntaires:");

        txt_brute_av_reduc_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_brute_av_reduc_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_brute_av_reduc_mod.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Ar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(154, 154, 154))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(143, 143, 143)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(81, 81, 81)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(jLabel27))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_cnaps_reduc_mod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_osief_reduc_mod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_irsa_reduc_mod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_totale_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(txt_avances_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17))
                        .addComponent(txt_brute_av_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel16)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_brute_av_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_avances_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cnaps_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_osief_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_irsa_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(txt_totale_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_ref_mod_reduc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enre_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_efacer_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_annuler_entrep_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)))
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_enre_reduc_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_efacer_reduc_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_annuler_entrep_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_ref_mod_reduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        select_nom_perso();
        allocation();
        txt_autres_reduc_mod.setText("0");
        txt_cession_sal_reduc_mod.setText("0");
        txt_nouri_loge_reduc_mod.setText("0");
        
    } catch (Exception ex) {
        Logger.getLogger(reduction_mod.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void btn_annuler_entrep_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annuler_entrep_modActionPerformed
    try {      
        
        this.dispose();
    } catch (Exception ex) {
        Logger.getLogger(reduction_mod.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_annuler_entrep_modActionPerformed

private void select_nom_perso() throws Exception, SQLException{
    con_db = new Connecter_bd();
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_reduc_mod.getText().toString();
    query = "select * from tab_perso where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String perso = rs.getString("nom_pre_perso");
       String num = rs.getString("num_perso");
       txt_nom_perso_reduc_mod.setText(perso);
       txt_num_perso_reduc2_mod.setText(num);
       select_sal_perso();
   } 
}
private void select_sal_perso() throws Exception, SQLException{
   //txt_num_perso_sup.removeAllItems();
   String num_p_sup = txt_num_perso_reduc_mod.getText().toString();
    con_db = new Connecter_bd();
    query = "select * from tab_contrat where num_perso='"+num_p_sup+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String sal_b_perso = rs.getString("sal_base_contrat").toString();
       txt_sal_base_reduc_mod.setText(sal_b_perso);
      // select_nom_perso();
   }else{
        
    } 
}
private void select_irsa() throws Exception, SQLException{
    
    con_db = new Connecter_bd();
    double min_sal_base = 250000;
    double irsa_default = 2000;
    double irsa;
    int vinght = 20;
    double sal_reste;
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_reduc_mod.getText().toString();
    query = "select * from tab_contrat where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String sal_base = rs.getString("sal_base_contrat");
       txt_sal_base_reduc_mod.setText(sal_base);
       double sal_base_reduc = Double.parseDouble(sal_base);
    if(sal_base_reduc<=min_sal_base){
    irsa = irsa_default;  
    String iras_final = Double.toString(irsa);
    txt_irsa_reduc_mod.setText(iras_final);
      }else{ 
    /*String cna = txt_cnaps_reduc.getText();
     String osi = txt_osief_reduc.getText();
     double cnaps = Double.parseDouble(cna);
     double osief = Double.parseDouble(osi);
     double sal_rs_all = (cnaps+osief);
     String ok = Double.toString(sal_rs_all);
     txt_iras_reduce.setText(ok);*/   
     double sal_reste2 = (sal_base_reduc-min_sal_base); 
    // double cnapsosief;
     String cna = txt_cnaps_reduc_mod.getText();
     String osi = txt_osief_reduc_mod.getText();
     double cnaps = Double.parseDouble(cna);
     double osief = Double.parseDouble(osi);
     double sal_cnaosi = (cnaps+osief);
     double sal_rs_all = (sal_reste2-sal_cnaosi);
     double taux_irsa_20 = (sal_rs_all*20);
     double taux_irsa_final = (taux_irsa_20/100);
     String alloc = txt_famille_reduc.getText();
     double alloc_fami = Double.parseDouble(alloc);
     double finale_irsa = (taux_irsa_final-alloc_fami);
     String afficer_irsa = Double.toString(finale_irsa);
     txt_irsa_reduc_mod.setText(afficer_irsa);
    
    }/*else{
      sal_reste = (sal_base_reduc-min_sal_base); 
    // double cnapsosief;
     String cna = txt_cnaps_reduc.getText();
     String osi = txt_osief_reduc.getText();
     double cnaps = Double.parseDouble(cna);
     double osief = Double.parseDouble(osi);
     double sal_cnaosi = (cnaps+osief);
     double sal_rs_all = (sal_reste-sal_cnaosi);
     double taux_irsa_20 = (sal_rs_all*20);
     double taux_irsa_final = (taux_irsa_20/100);
     double finale_irsa = (taux_irsa_final);
     String afficer_irsa = Double.toString(finale_irsa);
     txt_iras_reduce.setText(afficer_irsa);     
     }*/
    }else{
   JOptionPane.showMessageDialog(null,"Cet personnel doit être effectué à un contrat","Message",JOptionPane.WARNING_MESSAGE);     
    }
}
private void allocation() throws Exception{
        String num_p = txt_num_perso_reduc_mod.getText().toString();
        //String ms = txt_mois_avance.getSelectedItem().toString();
        con_db = new Connecter_bd();
        query = "select * from tab_perso where num_perso='"+num_p+"'";
        ResultSet rs = con_db.executeQuery(query);
        double vola_zaza = 4000;
      if(rs.next()){
        String nbr = rs.getString("nbr_enf_perso");
        double nbr_enf = Double.parseDouble(nbr);
        double somme =( nbr_enf*vola_zaza);
        String vola = Double.toString(somme);
        txt_famille_reduc.setText(vola);
      }else{
          
      }
}
private void select_sal_brute() throws Exception, SQLException{
    con_db = new Connecter_bd();
    int un = 1;
    int deux= 2;
    double brute_defaut = 0;
    double unpourcent,unpourcent_finale;
    double deuxpourcent,deuxpourcent_finale;
    //impot sur le revenu salaire annuel.
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_reduc_mod.getText().toString();
    query = "select * from tab_av where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String brute_av = rs.getString("totale_brute_av").toString();
       txt_brute_av_reduc_mod.setText(brute_av);
      double brute_ok = Double.parseDouble(brute_av);
      unpourcent = (brute_ok*un);
      unpourcent_finale = (unpourcent/100);
      String afficher_un = Double.toString(unpourcent_finale);
      deuxpourcent = (brute_ok*2);
      deuxpourcent_finale = (deuxpourcent/100);
      String affoicher_deux = Double.toString(deuxpourcent_finale);
      txt_cnaps_reduc_mod.setText(afficher_un);
      txt_osief_reduc_mod.setText(affoicher_deux);
      
   }else{
        txt_brute_av_reduc_mod.setText("0");
        String num_p2 = txt_num_perso_reduc_mod.getText().toString();
        query = "select * from tab_contrat where num_perso='"+num_p2+"'";
        ResultSet rs2 = con_db.executeQuery(query);
        if(rs2.next()){
        String sal_base = rs2.getString("sal_base_contrat");
        double brute_ok = Double.parseDouble(sal_base);
      unpourcent = (brute_ok*un);
      unpourcent_finale = (unpourcent/100);
      String afficher_un = Double.toString(unpourcent_finale);
      deuxpourcent = (brute_ok*2);
      deuxpourcent_finale = (deuxpourcent/100);
      String affoicher_deux = Double.toString(deuxpourcent_finale);
      txt_cnaps_reduc_mod.setText(afficher_un);
      txt_osief_reduc_mod.setText(affoicher_deux);
        }else{  
        }
    }
}
private void select_infos() throws Exception, SQLException{
    con_db = new Connecter_bd();
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_reduc_mod.getText().toString();
    query = "select * from tab_avance where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String num = rs.getString("num_perso");
   } 
}

public void select_avance() throws Exception{
   // String ms = txt_mois_reduc.getSelectedItem().toString();
    int ms = txt_mois_reduc_mod.getMonth();
    int mois = ms+1;
    int annee = txt_annee_reduc_mod.getYear();
    String an = Integer.toString(annee);
    String num_p = txt_num_perso_reduc_mod.getText().toString();
    con_db = new Connecter_bd();
    query = "select * from tab_avance where num_perso='"+num_p+"' and mois_avance='"+mois+"' and annee_avance='"+an+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
    String avance = rs.getString("total_avance");
    txt_avances_reduc_mod.setText(avance);
    }else{
    txt_avances_reduc_mod.setText("0.0");  
    }
}
    private void btn_enre_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enre_reduc_modActionPerformed
        //tsy tokony io le variable fa kamo be zah ra,avy da nagako @io avao.
        //fe mety avao se.
        String nb =  txt_cession_sal_reduc_mod.getText();
        String idm = txt_nouri_loge_reduc_mod.getText();
        String voca = txt_autres_reduc_mod.getText();
        if(nb.equals("")==true || idm.equals("")==true || voca.equals("")==true){
            JOptionPane.showMessageDialog(null,"Veillez remplir les champs  vides au mois mettez zéro (0.0) comme les autres","Message",JOptionPane.WARNING_MESSAGE);
        }else{
            double totale;
            String avance = txt_avances_reduc_mod.getText();
            String nouri_loge = txt_nouri_loge_reduc_mod.getText();
            String cess_sal = txt_cession_sal_reduc_mod.getText();
            String cnaps = txt_cnaps_reduc_mod.getText();
            String osief = txt_osief_reduc_mod.getText();
            String irsa = txt_irsa_reduc_mod.getText();
            String num_perso = txt_num_perso_reduc2_mod.getText();
            String autres = txt_autres_reduc_mod.getText();
            double autres_c =Double.parseDouble(autres);
            //convertisation en double
            double avance_c = Double.parseDouble(avance);
            double nouri_loge_c = Double.parseDouble(nouri_loge);
            double cesse_sal_c = Double.parseDouble(cess_sal);
            double cnaps_c = Double.parseDouble(cnaps);
            double osief_c = Double.parseDouble(osief);
            double irsa_c = Double.parseDouble(irsa);
            totale = (avance_c+nouri_loge_c+cesse_sal_c+cnaps_c+osief_c+irsa_c+autres_c);
            String totale_ok = Double.toString(totale);
            txt_totale_reduc_mod.setText(totale_ok);
            Date actuelle = new Date();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
            String periode_du = dt.format(txt_pdu_reduc_mod.getDate());
            String periode_au = dt.format(txt_pau_reduc_mod.getDate());
            String date_now = dateFormat.format(actuelle);
            //String mois_av = txt_mois_sup.getSelectedItem().toString();
            int annee = txt_annee_reduc_mod.getYear();
            int mw = txt_mois_reduc_mod.getMonth();
            int mws = mw+01;
            String mois_red = Integer.toString(mws);
            String annee_red = Integer.toString(annee);

            int infos = JOptionPane.showConfirmDialog(this,"Voullez-vous vraiment effectué cette opération de la réduction ?","Message",JOptionPane.YES_NO_OPTION);
            if(infos==JOptionPane.YES_OPTION){
                try {
                    String num_p = txt_num_perso_reduc_mod.toString();
                    con_db = new Connecter_bd();
                    query = "select * from tab_av where num_perso='"+num_p+"' and mois_av='"+mws+"' and annee_av='"+annee+"'";
                    //                    query = "select * from tab_av where num_perso='"+num_p+"' and mois_av='"+mws+"' and annee_av='"+annee+"'";
                    ResultSet rs = con_db.executeQuery(query);
                    if(rs.next()){
                        String totale_brute_av = rs.getString("totale_brute_av");
                        double brute = Double.parseDouble(totale_brute_av);
                        String totale_reduc = txt_totale_reduc_mod.getText();
                        double reduc = Double.parseDouble(totale_reduc);
                        double avance_add = Double.parseDouble(txt_avances_reduc_mod.getText());
                        if(brute>reduc){
                            //   classe_reduction clr = new classe_reduction(num_perso,date_now,mois_red,annee_red,periode_du,periode_au,cnaps_c,osief_c,irsa_c,cesse_sal_c,nouri_loge_c,autres_c,totale);
                            //  requet_reduction rqtreduc = new requet_reduction();
                            
                            try {
                                //  rqtreduc.ajouter(clr);
                           classe_reduction clr = new classe_reduction(num_perso,date_now,mois_red,annee_red,periode_du,periode_au,cnaps_c,osief_c,irsa_c,cesse_sal_c,nouri_loge_c,autres_c,avance_add,totale);
                           requet_reduction rqtreduc = new requet_reduction();
                           String ref = txt_ref_mod_reduc.getText();
                            rqtreduc.modifier(ref,clr);
                            
                            } catch (Exception ex) {
                                Logger.getLogger(reduction_add.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            JOptionPane.showMessageDialog(null,"Les informations ont été  bien enregistrées ","Message",JOptionPane.PLAIN_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Le totale de brute de salaire doit supérieur ou equale au totale  taxes et réduction","Message",JOptionPane.WARNING_MESSAGE);
                        }
                    }else{
                        String sal_base = txt_sal_base_reduc_mod.getText();
                        double salaire_base = Double.parseDouble(sal_base);
                        String totale_reduc = txt_totale_reduc_mod.getText();
                        double reduc = Double.parseDouble(totale_reduc);
                        double avance_add = Double.parseDouble(txt_avances_reduc_mod.getText());
                        if(salaire_base>reduc){
                            classe_reduction clr = new classe_reduction(num_perso,date_now,mois_red,annee_red,periode_du,periode_au,cnaps_c,osief_c,irsa_c,cesse_sal_c,nouri_loge_c,autres_c,avance_add,totale);
                            requet_reduction rqtreduc = new requet_reduction();
                           String ref = txt_ref_mod_reduc.getText();
                            rqtreduc.modifier(ref,clr);
                            JOptionPane.showMessageDialog(null,"Les informations ont été  bien enregistrées","Message",JOptionPane.PLAIN_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null,"Le totale de brute de salaire doit supérieur ou equale au totale  taxes et réduction","Message",JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    /* int ms = txt_mois_reduc.getMonth();
                    int mois = ms+1;
                    int annee = txt_annee_reduc.getYear();
                    String an = Integer.toString(annee);
                    String num_p = txt_num_perso_reduc.getSelectedItem().toString();
                    con_db = new Connecter_bd();
                    query = "select * from tab_av where num_perso='"+num_p+"' and mois_av='"+mois+"' and annee_av='"+an+"'";
                    ResultSet rs = con_db.executeQuery(query);
                    if(rs.next()){
                        String totale_brute_av = rs.getString("totale_brute_av");
                        txt_avances_reduc.setText(avance);
                        String totale_reduc = txt_totale_reduc.getText();
                        */
                    }    catch (SQLException ex) {
                        Logger.getLogger(reduction_add.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(reduction_add.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_btn_enre_reduc_modActionPerformed

    private void btn_ok_dt_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_dt_reduc_modActionPerformed
        if(((JTextField)txt_pdu_reduc_mod.getDateEditor().getUiComponent()).getText().equals("")==false ||
            ((JTextField)txt_pau_reduc_mod.getDateEditor().getUiComponent()).getText().equals("")==false){
            //pour l'année
            DateFormat dateFormat_an = new SimpleDateFormat("yyyy");
            Date pdu = txt_pdu_reduc_mod.getDate();
            String pdu2 = dateFormat_an.format(pdu);
            Date pau = txt_pau_reduc_mod.getDate();
            String pau2 = dateFormat_an.format(pau);
            int pan1_1 = Integer.parseInt(pdu2);
            int pan2_2 = Integer.parseInt(pau2);
            //pour le mois
            DateFormat dateFormat_ms = new SimpleDateFormat("MM");
            Date pdu_ms = txt_pdu_reduc_mod.getDate();
            String pdu1_ms = dateFormat_ms.format(pdu_ms);
            Date pau_ms = txt_pau_reduc_mod.getDate();
            String pau2_ms = dateFormat_ms.format(pau_ms);
            int pdu_ms1 = Integer.parseInt(pdu1_ms);
            int pau_ms1 = Integer.parseInt(pau2_ms);
            if((pan1_1==pan2_2) && (pdu_ms1 == pau_ms1)){
                Date date_now = new Date();
                DateFormat dateFormat_now_an = new SimpleDateFormat("yyyy");
                String dt_an_now = dateFormat_now_an.format(date_now);
                DateFormat dateFormat_now_mw = new SimpleDateFormat("MM");
                String dt_mw_now = dateFormat_now_mw.format(date_now);
                int an_now_1 = Integer.parseInt(dt_an_now);
                int mw_now_1 = Integer.parseInt(dt_mw_now);
                int an = txt_annee_reduc_mod.getYear();
                int mw = txt_mois_reduc_mod.getMonth();
                int mws= mw+01;
                if((mw_now_1==pdu_ms1) && (an_now_1==pan1_1) && (an==an_now_1) && (mws==mw_now_1)){
                    try {
                        select_avance();
                        select_sal_brute();
                        select_irsa();
                    } catch (Exception ex) {
                        Logger.getLogger(reduction_mod.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Le mois et l'année doivent être actuelle","Message",JOptionPane.WARNING_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(null,"Le mois et l'année de ce deux dates doivent être éguals","Message",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Veillez remplir les deux champs dates","Message",JOptionPane.WARNING_MESSAGE);
        }
        /*try {
            select_nom_perso();
            select_avance();
            select_sal_brute();
            select_irsa();
        } catch (Exception ex) {
            Logger.getLogger(reduction_add.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btn_ok_dt_reduc_modActionPerformed

    private void txt_nouri_loge_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nouri_loge_reduc_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nouri_loge_reduc_modActionPerformed

    private void btn_ok_reduc_final_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_reduc_final_modActionPerformed
        if(txt_num_perso_reduc2_mod.equals("")==true){
            JOptionPane.showMessageDialog(null,"Veillez approuvez le ","Message",JOptionPane.WARNING_MESSAGE);
        }else{

            double totale;
            String avance = txt_avances_reduc_mod.getText();
            String nouri_loge = txt_nouri_loge_reduc_mod.getText();
            String cess_sal = txt_cession_sal_reduc_mod.getText();
            String cnaps = txt_cnaps_reduc_mod.getText();
            String osief = txt_osief_reduc_mod.getText();
            String irsa = txt_irsa_reduc_mod.getText();
            //convertisation en double
            double avance_c = Double.parseDouble(avance);
            double nouri_loge_c = Double.parseDouble(nouri_loge);
            double cesse_sal_c = Double.parseDouble(cess_sal);
            double cnaps_c = Double.parseDouble(cnaps);
            double osief_c = Double.parseDouble(osief);
            double irsa_c = Double.parseDouble(irsa);
            totale = (avance_c+nouri_loge_c+cesse_sal_c+cnaps_c+osief_c+irsa_c);
            String totale_ok = Double.toString(totale);
            txt_totale_reduc_mod.setText(totale_ok);
    }//GEN-LAST:event_btn_ok_reduc_final_modActionPerformed
    }
    private void txt_irsa_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_irsa_reduc_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_irsa_reduc_modActionPerformed

    private void txt_osief_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_osief_reduc_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_osief_reduc_modActionPerformed

    private void txt_cnaps_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnaps_reduc_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnaps_reduc_modActionPerformed

    private void txt_avances_reduc_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avances_reduc_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avances_reduc_modActionPerformed

    private void txt_famille_reducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_famille_reducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_famille_reducActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reduction_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reduction_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reduction_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reduction_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reduction_mod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annuler_entrep_mod;
    private javax.swing.JButton btn_efacer_reduc_mod;
    private javax.swing.JButton btn_enre_reduc_mod;
    private javax.swing.JButton btn_ok_dt_reduc_mod;
    private javax.swing.JButton btn_ok_reduc_final_mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public com.toedter.calendar.JYearChooser txt_annee_reduc_mod;
    public javax.swing.JTextField txt_autres_reduc_mod;
    public javax.swing.JTextField txt_avances_reduc_mod;
    public javax.swing.JTextField txt_brute_av_reduc_mod;
    public javax.swing.JTextField txt_cession_sal_reduc_mod;
    public javax.swing.JTextField txt_cnaps_reduc_mod;
    private javax.swing.JTextField txt_famille_reduc;
    public javax.swing.JTextField txt_irsa_reduc_mod;
    public com.toedter.calendar.JMonthChooser txt_mois_reduc_mod;
    public javax.swing.JTextField txt_nom_perso_reduc_mod;
    public javax.swing.JTextField txt_nouri_loge_reduc_mod;
    public javax.swing.JTextField txt_num_perso_reduc2_mod;
    public javax.swing.JTextField txt_num_perso_reduc_mod;
    public javax.swing.JTextField txt_osief_reduc_mod;
    public com.toedter.calendar.JDateChooser txt_pau_reduc_mod;
    public com.toedter.calendar.JDateChooser txt_pdu_reduc_mod;
    public javax.swing.JTextField txt_ref_mod_reduc;
    public javax.swing.JTextField txt_sal_base_reduc_mod;
    public javax.swing.JTextField txt_totale_reduc_mod;
    private javax.swing.JLabel txt_vaca_sup;
    // End of variables declaration//GEN-END:variables
}
