/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forme;

import com.classe.DeuxChiffresApresVirgule;
import com.classe.classe_suplemetaire;
import com.requete.Connecter_bd;
import com.requete.connections;
import com.requete.requet_suplementaire;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author VONINAHITRA
 */
public class suplementaire_mod extends javax.swing.JFrame {
private String query;
private Connecter_bd con_db;
connections maCon = new connections();
ResultSet rs;
PreparedStatement ps;
Statement st;
Connection conc;
    /**
     * Creates new form NewJFrame
     */
    public suplementaire_mod() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txt_ref_mod_sup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_annuler_entrep_mod = new javax.swing.JButton();
        btn_effacer_mod = new javax.swing.JButton();
        btn_valider_sup_mod = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_annee_sup = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        txt_pdu_sup_mod = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txt_pau_sup_mod = new com.toedter.calendar.JDateChooser();
        btn_ok_dt_sup_mod = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_mois_sup = new com.toedter.calendar.JMonthChooser();
        txt_num_perso_sup_mod = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_nom_perso_sup_mod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_num_perso_sup2_mod = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_sal_base_sup_mod = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_nbrhrs_sup_mod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_idemnite_sup_mod = new javax.swing.JTextField();
        txt_vacation_sup_mod = new javax.swing.JTextField();
        txt_vaca_sup = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_heure40_mod = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_anciente_mod = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btn_ok_dt_sup_final_mod = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_totale_brute_sup_mod = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_val_totale_sup_mod = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_val_8_sup_mod = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_val_8_plus_sup_mod = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_plus40_mod = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_ref_mod_sup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICATION AVANTAGES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Money_Transfer_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_annuler_entrep_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_annuler_entrep_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_annuler_entrep_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_annuler_entrep_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Close_Window_25px.png"))); // NOI18N
        btn_annuler_entrep_mod.setText("Annuler/Fermer");
        btn_annuler_entrep_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_annuler_entrep_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annuler_entrep_modActionPerformed(evt);
            }
        });

        btn_effacer_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_effacer_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_effacer_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_effacer_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Reset_25px.png"))); // NOI18N
        btn_effacer_mod.setText("Effacer");
        btn_effacer_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_valider_sup_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_valider_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_valider_sup_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_valider_sup_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Checkmark_25px.png"))); // NOI18N
        btn_valider_sup_mod.setText("Enregister");
        btn_valider_sup_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_valider_sup_mod.setMaximumSize(new java.awt.Dimension(20, 29));
        btn_valider_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valider_sup_modActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Période et date d'vances", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mois du :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Année :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Période du");

        txt_pdu_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("au ");

        txt_pau_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_ok_dt_sup_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_dt_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_dt_sup_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_dt_sup_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Approval_25px.png"))); // NOI18N
        btn_ok_dt_sup_mod.setText("Approuver");
        btn_ok_dt_sup_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_dt_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_dt_sup_modActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("N° matricule :");

        txt_mois_sup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_num_perso_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_num_perso_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_num_perso_sup_mod.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_annee_sup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_mois_sup, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_num_perso_sup_mod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pau_sup_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_pdu_sup_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addComponent(btn_ok_dt_sup_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel11)
                        .addComponent(txt_num_perso_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_pdu_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mois_sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_pau_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_annee_sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_ok_dt_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Période et date d'vances", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txt_nom_perso_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nom_perso_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_perso_sup_mod.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Nom et prénom :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("N° matricule :");

        txt_num_perso_sup2_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_num_perso_sup2_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_num_perso_sup2_mod.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Salaire de base :");

        txt_sal_base_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sal_base_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_sal_base_sup_mod.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Ar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_sal_base_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addComponent(txt_num_perso_sup2_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_perso_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_nom_perso_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_num_perso_sup2_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_sal_base_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Période et date d'vances", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txt_nbrhrs_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Primes et indemnités :");

        txt_idemnite_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_idemnite_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idemnite_sup_modActionPerformed(evt);
            }
        });

        txt_vacation_sup_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_vaca_sup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_vaca_sup.setText("Vocation ou pièces :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Ar");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Ar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Heures suplementaires(30% et 50%):");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Hrs");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Hrs (Pour le gardien de nuit)");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Heures suplementaires(40%):");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Ancienté(e) :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Ar");

        btn_ok_dt_sup_final_mod.setBackground(new java.awt.Color(0, 102, 153));
        btn_ok_dt_sup_final_mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ok_dt_sup_final_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok_dt_sup_final_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Ok_25px.png"))); // NOI18N
        btn_ok_dt_sup_final_mod.setText("Valider");
        btn_ok_dt_sup_final_mod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok_dt_sup_final_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_dt_sup_final_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel31)
                    .addComponent(jLabel5)
                    .addComponent(jLabel27)
                    .addComponent(txt_vaca_sup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_ok_dt_sup_final_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_heure40_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txt_nbrhrs_sup_mod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_idemnite_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_vacation_sup_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txt_anciente_mod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nbrhrs_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_heure40_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_idemnite_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_anciente_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_vacation_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txt_vaca_sup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok_dt_sup_final_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)), "Période et date d'vances", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Total de brutes :");

        txt_totale_brute_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_totale_brute_sup_mod.setEnabled(false);
        txt_totale_brute_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totale_brute_sup_modActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Ar");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Total de majorations:");

        txt_val_totale_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_val_totale_sup_mod.setEnabled(false);
        txt_val_totale_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_val_totale_sup_modActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Ar");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Majoration 50% :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Majoration 30% :");

        txt_val_8_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_val_8_sup_mod.setEnabled(false);
        txt_val_8_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_val_8_sup_modActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Ar");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Ar");

        txt_val_8_plus_sup_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_val_8_plus_sup_mod.setEnabled(false);
        txt_val_8_plus_sup_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_val_8_plus_sup_modActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Majoration 40%:");

        txt_plus40_mod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_plus40_mod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_plus40_mod.setEnabled(false);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Ar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel9)
                    .addComponent(jLabel28)
                    .addComponent(jLabel22)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_plus40_mod)
                            .addComponent(txt_val_8_plus_sup_mod)
                            .addComponent(txt_val_8_sup_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addComponent(txt_val_totale_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_totale_brute_sup_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel32)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_val_8_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_plus40_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_val_8_plus_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_val_totale_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_totale_brute_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(24, 24, 24))
        );

        txt_ref_mod_sup.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_ref_mod_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ref_mod_supActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txt_ref_mod_sup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_valider_sup_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_effacer_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_annuler_entrep_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_valider_sup_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_ref_mod_sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btn_effacer_mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_annuler_entrep_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        select_sal_perso();
//        // TODO add your handling code here:
//        txt_nbrhrs_sup_mod.setText("0.0");
//        txt_idemnite_sup_mod.setText("0.0");
//        txt_vacation_sup_mod.setText("0.0");
////        select_sal_perso();
////        select_nom_perso();    
////        String val8 = txt_val_8_sup_mod.getText();
////        String val_plus8 = txt_val_8_plus_sup_mod.getText();
////        double val1 = Double.parseDouble(val8);
////        double val2 = Double.parseDouble(val_plus8);
////        double totale = (val1+val2);
////        String total_sup = Double.toString(totale);
////        txt_val_totale_sup_mod.setText(total_sup);
//        //select_sal_perso();
//        //select_nom_perso();
//        
    } catch (Exception ex) {
        Logger.getLogger(suplementaire_mod.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void select_sal_perso() throws Exception, SQLException{
   //txt_num_perso_sup.removeAllItems();
   String num_p_sup = txt_num_perso_sup_mod.getText();
    con_db = new Connecter_bd();
    query = "select * from tab_contrat where num_perso='"+num_p_sup+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String sal_b_perso = rs.getString("sal_base_contrat").toString();
       txt_sal_base_sup_mod.setText(sal_b_perso);
      select_nom_perso();
   }else{
        
    } 
}

    private void select_nom_perso() throws Exception, SQLException{
    con_db = new Connecter_bd();
     //txt_num_perso_avcance.removeAllItems();
    String num_p = txt_num_perso_sup2_mod.getText();
    query = "select * from tab_perso where num_perso='"+num_p+"'";
    ResultSet rs = con_db.executeQuery(query);
    if(rs.next()){
       String perso = rs.getString("nom_pre_perso");
       //String num = rs.getString("num_perso");
       txt_nom_perso_sup_mod.setText(perso);
       //txt_num_perso_sup2_mod.setText(num);
       //txt_nbrhrs_sup.enable(true);
       //txt_idemnite_sup.enable(true);
       //txt_vacation_sup.enable(true);
//        txt_famille_sup.enable(true);
   } 
}
private void verifier_mod() throws Exception{
String num_p = txt_num_perso_sup2_mod.getText();
Date actuelle = new Date();
DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
String periode_du = dt.format(txt_pdu_sup_mod.getDate());
String periode_au = dt.format(txt_pau_sup_mod.getDate());
String date_now = dateFormat.format(actuelle);
//String mois_av = txt_mois_sup.getSelectedItem().toString();
int annee = txt_annee_sup.getYear();
int mw = txt_mois_sup.getMonth();
int mws = mw+01;
String mois = Integer.toString(mws);
String annee_av = Integer.toString(annee);
String idemnite = txt_idemnite_sup_mod.getText();
double idemnite_av = Double.parseDouble(idemnite);
String voca = txt_vacation_sup_mod.getText();
double voca_av = Double.parseDouble(voca);
String nbr = txt_nbrhrs_sup_mod.getText();
int nbr_av = Integer.parseInt(nbr);
String hrsval8= txt_val_8_sup_mod.getText();
double hrsval8_av = Double.parseDouble(hrsval8);
String hrsvalplus8 = txt_val_8_plus_sup_mod.getText();
double hrsvalplus8_av = Double.parseDouble(hrsvalplus8);
//String fami = txt_famille_sup.getText();
//double famille = Double.parseDouble(fami); String finalez = DeuxChiffresApresVirgule.ChiffresApresVirgule(finale);
String totale_brute = txt_totale_brute_sup_mod.getText();
double totale_brute_av = Double.parseDouble(totale_brute);
String ref = txt_ref_mod_sup.getText();
//classe_suplemetaire clas = new classe_suplemetaire(num_p,date_now,mois, annee_av, periode_du, periode_au, idemnite_av, voca_av,nbr_av, hrsval8_av, hrsvalplus8_av, totale_brute_av);
//requet_suplementaire rqtsup= new requet_suplementaire();
////rqtsup.ajouter(clas);
//rqtsup.modifier(ref,clas);
JOptionPane.showMessageDialog(null,"Les informations ont été  bien enregistrées","Message",JOptionPane.PLAIN_MESSAGE);  
//tena mbola miasa be io code ambany natao commentaire io.
perso_entrep_contrat_avance_forme ok = new perso_entrep_contrat_avance_forme();
ok.config_tab_avantage();
}
    private void btn_annuler_entrep_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annuler_entrep_modActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_annuler_entrep_modActionPerformed

    private void btn_valider_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valider_sup_modActionPerformed
        String nb =  txt_nbrhrs_sup_mod.getText();
        String idm = txt_idemnite_sup_mod.getText();
        String voca = txt_vacation_sup_mod.getText();
        //String fami = txt_famille_sup_mod.getText();
        if(nb.equals("")==true || idm.equals("")==true || voca.equals("")==true){
            JOptionPane.showMessageDialog(null,"Veillez remplir les champs sont vides sur heures suplémentaires et avantages","Message",JOptionPane.WARNING_MESSAGE);
        }else{
            if(nb.equals("")==true && idm.equals("")==true && voca.equals("")==true){
            JOptionPane.showMessageDialog(null,"Veillez saisir le valeur plus de Zéro (0)  pour effectué cette opération\n au mois l'un des chapms sur heures supléméntaires \n Et avantages.","Message",JOptionPane.WARNING_MESSAGE);
            }else{ //calcule_all();
                int infos = JOptionPane.showConfirmDialog(this,"Voullez-vous vraiment modifier ?","Message",JOptionPane.YES_NO_OPTION);
                if(infos==JOptionPane.YES_OPTION){
                    try {
                       ajout_verifier_av();
                    } catch (Exception ex) {
                     //   Logger.getLogger(suplementaire_mod.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{

                }
            }
        }
    }//GEN-LAST:event_btn_valider_sup_modActionPerformed

    private void btn_ok_dt_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_dt_sup_modActionPerformed
        if(((JTextField)txt_pdu_sup_mod.getDateEditor().getUiComponent()).getText().equals("")==false ||
            ((JTextField)txt_pau_sup_mod.getDateEditor().getUiComponent()).getText().equals("")==false){
            //pour l'année
            DateFormat dateFormat_an = new SimpleDateFormat("yyyy");
            Date pdu = txt_pdu_sup_mod.getDate();
            String pdu2 = dateFormat_an.format(pdu);
            Date pau = txt_pau_sup_mod.getDate();
            String pau2 = dateFormat_an.format(pau);
            int pan1_1 = Integer.parseInt(pdu2);
            int pan2_2 = Integer.parseInt(pau2);
            //pour le mois
            DateFormat dateFormat_ms = new SimpleDateFormat("MM");
            Date pdu_ms = txt_pdu_sup_mod.getDate();
            String pdu1_ms = dateFormat_ms.format(pdu_ms);
            Date pau_ms = txt_pau_sup_mod.getDate();
            String pau2_ms = dateFormat_ms.format(pau_ms);
            int pdu_ms1 = Integer.parseInt(pdu1_ms);
            int pau_ms1 = Integer.parseInt(pau2_ms);
            if((pan1_1==pan2_2) && (pdu_ms1 == pau_ms1)){
                Date date_now = new Date();
                DateFormat dateFormat_now_an = new SimpleDateFormat("yyyy");
                String dt_an_now = dateFormat_now_an.format(date_now);
                DateFormat dateFormat_now_mw = new SimpleDateFormat("MM");
                String dt_mw_now = dateFormat_now_mw.format(date_now);
                int an_now_1 = Integer.parseInt(dt_an_now);
                int mw_now_1 = Integer.parseInt(dt_mw_now);
                int an = txt_annee_sup.getYear();
                int mw = txt_mois_sup.getMonth();
                int mws= mw+01;
                if((mw_now_1==pdu_ms1) && (an_now_1==pan1_1) && (an==an_now_1) && (mws==mw_now_1)){
                    try {
                        select_sal_perso();
//                        select_nom_perso();
                        //allocation();
                        btn_ok_dt_sup_final_mod.enable(true);
                    } catch (Exception ex) {
                        Logger.getLogger(suplementaire_mod.class.getName()).log(Level.SEVERE, null, ex);
                    }
                        }
                else{
                    JOptionPane.showMessageDialog(null,"Le mois et l'année doivent être actuelle","Message",JOptionPane.WARNING_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(null,"Le mois et l'année de ce deux dates doivent être éguals","Message",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Veillez remplir les deux champs dates","Message",JOptionPane.WARNING_MESSAGE);
        }

        /*try {
            select_sal_perso();
            select_nom_perso();
        } catch (Exception ex) {
            Logger.getLogger(suplementaire_add.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btn_ok_dt_sup_modActionPerformed

    private void txt_idemnite_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idemnite_sup_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idemnite_sup_modActionPerformed

    private void btn_ok_dt_sup_final_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_dt_sup_final_modActionPerformed
        /* txt_nbrhrs_sup.enable(true);
        txt_idemnite_sup.enable(true);
        txt_vacation_sup.enable(true);
        txt_famille_sup.enable(true);*/
        String nb =  txt_nbrhrs_sup_mod.getText();
        String idm = txt_idemnite_sup_mod.getText();
        String voca = txt_vacation_sup_mod.getText();
//        String fami = txt_famille_sup_mod.getText();
        if(nb.equals("")==true || idm.equals("")==true || voca.equals("")==true){
            JOptionPane.showMessageDialog(null,"Veillez remplir les champs  vides","Message",JOptionPane.WARNING_MESSAGE);
        }else{
            if(nb.equals("")==true && idm.equals("")==true && voca.equals("")==true){
                JOptionPane.showMessageDialog(null,"Veillez saisir le valeur plus de Zéro (0) sur les champs vide pour effectué cette opération\n au mois l'un des champs","Message",JOptionPane.WARNING_MESSAGE);
            }else{
                 calcule_all();
                 quarente();
                 sommes();
            }

        }
    }//GEN-LAST:event_btn_ok_dt_sup_final_modActionPerformed
private void quarente(){
    double conste = 173.33; 
    int hure40 =Integer.parseInt(txt_heure40_mod.getText());
    String sal_base = txt_sal_base_sup_mod.getText();
    double sal_base_d = Double.parseDouble(sal_base);
     //pourquarante
    double val_quarante =(sal_base_d/conste);
    double ok40 = (val_quarante*hure40);
    double quarente =(ok40*40);
    double final_40 = (quarente/100);
    double finale40 = (final_40+ok40);
     String totale40 = DeuxChiffresApresVirgule.ChiffresApresVirgule(finale40);
     txt_plus40_mod.setText(totale40);
}
private void sommes(){
    double aciente =Double.parseDouble(txt_anciente_mod.getText());
    double idemnite=Double.parseDouble(txt_idemnite_sup_mod.getText());
    double vocation =Double.parseDouble(txt_vacation_sup_mod.getText());
    double val8 =Double.parseDouble(txt_val_8_sup_mod.getText());
    double val_plus8 =Double.parseDouble(txt_val_8_plus_sup_mod.getText());
    double val_40 = Double.parseDouble(txt_plus40_mod.getText());
    double sal_base =Double.parseDouble(txt_sal_base_sup_mod.getText());
    double majoration =(val8+val_plus8+val_40);
     String maj= DeuxChiffresApresVirgule.ChiffresApresVirgule(majoration);
     txt_val_totale_sup_mod.setText(maj);
    double sommes =(aciente+idemnite+vocation+val8+val_plus8+val_40+sal_base);
    String total= DeuxChiffresApresVirgule.ChiffresApresVirgule(sommes);
    txt_totale_brute_sup_mod.setText(total);
}

public void calcule_all(){
    txt_val_8_plus_sup_mod.setText("0");
    quarente();
    DecimalFormat df = new DecimalFormat("0.00");
    df.setRoundingMode(RoundingMode.HALF_UP);
    double conste = 173.33;
   //double conste = 174;
    int huite = 8;
    double valeurheure;
    double ok;
    double trente;
    double ok_final;
    double finale;
    double cinquante;
    String nbrheur = txt_nbrhrs_sup_mod.getText();
    int heure_totale_d = Integer.parseInt(nbrheur);
    String sal_base = txt_sal_base_sup_mod.getText();
    double sal_base_d = Double.parseDouble(sal_base);
if(heure_totale_d<=huite){
    valeurheure = (sal_base_d/conste);
    ok = (valeurheure*heure_totale_d);   
    trente = (ok*30);  
    ok_final = (trente/100);
    finale = (ok_final+ok);
    //arrondissement
    //DecimalFormat df = new DecimalFormat("#.##");
    //df.setRoundingMode(RoundingMode.HALF_UP);
    //String totale = Double.toString(DeuxChiffresApresVirgule.ChiffresApresVirgule(finale));
    String totale = DeuxChiffresApresVirgule.ChiffresApresVirgule(finale);
    txt_val_8_sup_mod.setText(totale);
//    txt_val_totale_sup.setText(totale);
//    txt_totale_brute_sup
//String fami = txt_famille_sup.getText();
//double famille = Double.parseDouble(fami);
//double bru = (idemnite+vocation+finale+sal_base_d);
//String brutes = Double.toString(bru);
//String brutes = df.format(bru);
//String brutes = DeuxChiffresApresVirgule.ChiffresApresVirgule(bru);
//quarente();
}else{
     int total_intiale = (heure_totale_d - huite);
valeurheure = (sal_base_d/conste);
ok = (valeurheure*total_intiale);
cinquante = (ok*50);
ok_final = (cinquante/100);
finale = (ok_final+ok);  
//DecimalFormat df = new DecimalFormat("#.##");
    //df.setRoundingMode(RoundingMode.HALF_UP);
double ok2 = (valeurheure*huite);
double trente2 = (ok2*30);
double ok_finale2 = (trente2/100);
double finale2 = (ok_finale2+ok2);
double sommes = (finale+finale2);
String totaleautres = Double.toString(finale);
String totale8z =Double.toString(finale2);
//String somme_totale = Double.toString(sommes);
//arrondissement
//String totaleautres = df.format(finale);
//String totale8 =df.format(finale2);
//tring somme_totale = df.format(sommes);
String totale8 = DeuxChiffresApresVirgule.ChiffresApresVirgule(finale2);
txt_val_8_sup_mod.setText(totale8);
String finalez = DeuxChiffresApresVirgule.ChiffresApresVirgule(finale);
txt_val_8_plus_sup_mod.setText(finalez);
//String sommez= DeuxChiffresApresVirgule.ChiffresApresVirgule(sommes);
//txt_val_totale_sup.setText(sommez);
//String ide = txt_idemnite_sup.getText();
//double idemnite = Double.parseDouble(ide);
//String voc = txt_vacation_sup.getText();
//double vocation = Double.parseDouble(voc);
////String fami = txt_famille_sup.getText();
////double famille = Double.parseDouble(fami);
//String brutes = Double.toString(bru);
   }
//quarente();
}

public void ajout_verifier_av() {

    try {
        String num_p = txt_num_perso_sup2_mod.getText();
        Date actuelle = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        String periode_du = dt.format(txt_pdu_sup_mod.getDate());
        String periode_au = dt.format(txt_pau_sup_mod.getDate());
        String date_now = dateFormat.format(actuelle);
//String mois_av = txt_mois_sup.getSelectedItem().toString();
int annee = txt_annee_sup.getYear();
int mw = txt_mois_sup.getMonth();
int mws = mw+01;
String mois = Integer.toString(mws);
String annee_av = Integer.toString(annee);
int heur30_40 = Integer.parseInt(txt_nbrhrs_sup_mod.getText());
int heur40 =Integer.parseInt(txt_heure40_mod.getText());
double aciente =Double.parseDouble(txt_anciente_mod.getText());
double idemnite=Double.parseDouble(txt_idemnite_sup_mod.getText());
double vocation =Double.parseDouble(txt_vacation_sup_mod.getText());
double val8 =Double.parseDouble(txt_val_8_sup_mod.getText());
double val_plus8 =Double.parseDouble(txt_val_8_plus_sup_mod.getText());
double val_40 = Double.parseDouble(txt_plus40_mod.getText());
//    double sal_base =Double.parseDouble(txt_sal_base_sup.getText());
double sommes = Double.parseDouble(txt_totale_brute_sup_mod.getText());
String  ref= txt_num_perso_sup_mod.getText();
//   JOptionPane.showMessageDialog(null,"La modification a été bien effectué ","Message",JOptionPane.PLAIN_MESSAGE); 
classe_suplemetaire clas = new classe_suplemetaire(num_p,date_now,mois,annee_av,periode_du,periode_au,idemnite,vocation,aciente,heur30_40,heur40,val8,val_plus8,val_40,sommes);
requet_suplementaire rqtmod= new requet_suplementaire();
rqtmod.modifier(ref,clas);
JOptionPane.showMessageDialog(null,"La modification a été bien effectué ","Message",JOptionPane.PLAIN_MESSAGE);  
//tena mbola miasa be io code ambany natao commentaire io.
/*classe_suplemetaire cls = new classe_suplemetaire(num_p,date_now , mois_av, annee_av,periode_du,periode_au, idemnite_av, voca_av, nbr_av, hrsval8_av, hrsvalplus8_av, totale_brute_av);
requet_suplementaire rqtsup = new requet_suplementaire();
rqtsup.ajouter(cls);
JOptionPane.showMessageDialog(null,"L'avatage a été bien enregistré ","Message",JOptionPane.PLAIN_MESSAGE);
/* String num_p_av = txt_num_perso_sup2.getText();
String mois_av = txt_mois_sup.getSelectedItem().toString();
int annee= txt_annee_sup.getYear();
String annee_av = Integer.toString(annee);
SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
String dtdu = dt.format(txt_pdu_sup.getDate());
String dtau = dt.format(txt_pau_sup.getDate());
String netpay_av = txt_netpay_avance.getText();
Double netp = Double.parseDouble(netpay_av)*/
    } catch (Exception ex) {
        Logger.getLogger(suplementaire_mod.class.getName()).log(Level.SEVERE, null, ex);
    }
}

//public void calcule_all(){
//    double conste = 173.33;
//    int huite = 8;
//    double valeurheure;
//    double ok;
//    double trente;
//    double ok_final;
//    double finale;
//    double cinquante;
//    String nbrheur = txt_nbrhrs_sup_mod.getText();
//    int heure_totale_d = Integer.parseInt(nbrheur);
//    String sal_base = txt_sal_base_sup_mod.getText();
//    double sal_base_d = Double.parseDouble(sal_base);
//if(heure_totale_d<=huite){
//    valeurheure = (sal_base_d/conste);
//    ok = (valeurheure*heure_totale_d);   
//    trente = (ok*30);  
//    ok_final = (trente/100);
//    finale = (ok_final+ok);
//    //DecimalFormat df = new DecimalFormat("#.##");
//    //df.setRoundingMode(RoundingMode.HALF_UP);
//    //String totale = Double.toString(finale);
//    String totale = Double.toString(finale);
//    txt_val_8_sup_mod.setText(totale);
//    txt_val_totale_sup_mod.setText(totale);
//String ide = txt_idemnite_sup_mod.getText();
//double idemnite = Double.parseDouble(ide);
//String voc = txt_vacation_sup_mod.getText();
//double vocation = Double.parseDouble(voc);
////String fami = txt_famille_sup.getText();
////double famille = Double.parseDouble(fami);
//double bru = (idemnite+vocation+finale+sal_base_d);
////String brutes = Double.toString(bru);
//String brutes = Double.toString(bru);
//txt_totale_brute_sup_mod.setText(brutes);
//
//}else{
//     int total_intiale = (heure_totale_d - huite);
//valeurheure = (sal_base_d/conste);
//ok = (valeurheure*total_intiale);
//cinquante = (ok*50);
//ok_final = (cinquante/100);
//finale = (ok_final+ok);  
//double ok2 = (valeurheure*huite);
//double trente2 = (ok2*30);
//double ok_finale2 = (trente2/100);
//double finale2 = (ok_finale2+ok2);
//double sommes = (finale+finale2);
////DecimalFormat df = new DecimalFormat("#.##");
//   // df.setRoundingMode(RoundingMode.HALF_UP);
//String totaleautres = Double.toString(finale);
//String totale8 =Double.toString(finale2);
//String somme_totale = Double.toString(sommes);
//txt_val_8_sup_mod.setText(totale8);
//txt_val_8_plus_sup_mod.setText(totaleautres);
//txt_val_totale_sup_mod.setText(somme_totale);
//String ide = txt_idemnite_sup_mod.getText();
//double idemnite = Double.parseDouble(ide);
//String voc = txt_vacation_sup_mod.getText();
//double vocation = Double.parseDouble(voc);
////String fami = txt_famille_sup.getText();
////double famille = Double.parseDouble(fami);
//double bru = (idemnite+vocation+sommes+sal_base_d);
//String brutes = Double.toString(bru);
//txt_totale_brute_sup_mod.setText(brutes);
//   }
//}
    private void txt_totale_brute_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totale_brute_sup_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totale_brute_sup_modActionPerformed

    private void txt_val_totale_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_val_totale_sup_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_val_totale_sup_modActionPerformed

    private void txt_val_8_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_val_8_sup_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_val_8_sup_modActionPerformed

    private void txt_val_8_plus_sup_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_val_8_plus_sup_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_val_8_plus_sup_modActionPerformed

    private void txt_ref_mod_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ref_mod_supActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ref_mod_supActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suplementaire_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suplementaire_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suplementaire_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suplementaire_mod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suplementaire_mod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annuler_entrep_mod;
    private javax.swing.JButton btn_effacer_mod;
    private javax.swing.JButton btn_ok_dt_sup_final_mod;
    private javax.swing.JButton btn_ok_dt_sup_mod;
    private javax.swing.JButton btn_valider_sup_mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JTextField txt_anciente_mod;
    private com.toedter.calendar.JYearChooser txt_annee_sup;
    public javax.swing.JTextField txt_heure40_mod;
    public javax.swing.JTextField txt_idemnite_sup_mod;
    private com.toedter.calendar.JMonthChooser txt_mois_sup;
    public javax.swing.JTextField txt_nbrhrs_sup_mod;
    public javax.swing.JTextField txt_nom_perso_sup_mod;
    public javax.swing.JTextField txt_num_perso_sup2_mod;
    public javax.swing.JTextField txt_num_perso_sup_mod;
    public com.toedter.calendar.JDateChooser txt_pau_sup_mod;
    public com.toedter.calendar.JDateChooser txt_pdu_sup_mod;
    public javax.swing.JTextField txt_plus40_mod;
    public javax.swing.JTextField txt_ref_mod_sup;
    public javax.swing.JTextField txt_sal_base_sup_mod;
    public javax.swing.JTextField txt_totale_brute_sup_mod;
    private javax.swing.JLabel txt_vaca_sup;
    public javax.swing.JTextField txt_vacation_sup_mod;
    public javax.swing.JTextField txt_val_8_plus_sup_mod;
    public javax.swing.JTextField txt_val_8_sup_mod;
    public javax.swing.JTextField txt_val_totale_sup_mod;
    // End of variables declaration//GEN-END:variables
}
