/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forme;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.requete.Connecter_bd;
import com.requete.Connexion;
import com.requete.connections;
import com.requete.requet_user;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author VONIANAHITRA
 */
public class user_liste extends javax.swing.JFrame {
ResultSet rs;
ResultSet rse;
PreparedStatement ps;
PreparedStatement pse;
Statement st;
Statement ste;
Connection conc;
Connecter_bd con_db = new Connecter_bd();
connections maCon = new connections();
String query;
//Congifiration de la table
public  DefaultTableModel tab_user;
private String user;
private String pwd;
private String privillege;
    /**
    /**
     * Creates new form user_liste
     */
    public user_liste() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_utilisateur = new javax.swing.JTable();
        btn_auth5 = new javax.swing.JButton();
        btn_auth4 = new javax.swing.JButton();
        btn_auth2 = new javax.swing.JButton();
        btn_auth1 = new javax.swing.JButton();
        btn_auth = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES UTILISATEURS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/icons8_Add_User_Male_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        table_utilisateur.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_utilisateur.setRowHeight(25);
        jScrollPane2.setViewportView(table_utilisateur);

        btn_auth5.setBackground(new java.awt.Color(0, 102, 153));
        btn_auth5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_auth5.setForeground(new java.awt.Color(255, 255, 255));
        btn_auth5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Close_Window_25px.png"))); // NOI18N
        btn_auth5.setText("Annuler/Fermer");
        btn_auth5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_auth5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auth5ActionPerformed(evt);
            }
        });

        btn_auth4.setBackground(new java.awt.Color(0, 102, 153));
        btn_auth4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_auth4.setForeground(new java.awt.Color(255, 255, 255));
        btn_auth4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Delete_25px.png"))); // NOI18N
        btn_auth4.setText("Supprimer");
        btn_auth4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_auth4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auth4ActionPerformed(evt);
            }
        });

        btn_auth2.setBackground(new java.awt.Color(0, 102, 153));
        btn_auth2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_auth2.setForeground(new java.awt.Color(255, 255, 255));
        btn_auth2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Edit_25px.png"))); // NOI18N
        btn_auth2.setText("Modifier");
        btn_auth2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_auth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auth2ActionPerformed(evt);
            }
        });

        btn_auth1.setBackground(new java.awt.Color(0, 102, 153));
        btn_auth1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_auth1.setForeground(new java.awt.Color(255, 255, 255));
        btn_auth1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Plus_25px.png"))); // NOI18N
        btn_auth1.setText("Nouveau");
        btn_auth1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_auth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auth1ActionPerformed(evt);
            }
        });

        btn_auth.setBackground(new java.awt.Color(0, 102, 153));
        btn_auth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_auth.setForeground(new java.awt.Color(255, 255, 255));
        btn_auth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/icons8_Synchronize_25px_1.png"))); // NOI18N
        btn_auth.setText("Actualiser");
        btn_auth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_auth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_authActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_auth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_auth1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_auth2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_auth4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_auth5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_auth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_auth1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_auth2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_auth4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_auth5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        config_tab_perso();
    } catch (Exception ex) {
        Logger.getLogger(user_liste.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btn_authActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_authActionPerformed
    try {
        config_tab_perso();
    } catch (Exception ex) {
        Logger.getLogger(user_liste.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_authActionPerformed

    private void btn_auth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auth1ActionPerformed
        // TODO add your handling code here:
        user_add ua = new user_add();
        ua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_auth1ActionPerformed
   public void config_tab_perso() throws Exception{
        tab_user = new DefaultTableModel();
        tab_user.addColumn("Utilisateur");
        tab_user.addColumn("Mot de passe");
        tab_user.addColumn("Privillège");
        JTableHeader tb = table_utilisateur.getTableHeader();
        tb.setBackground(new Color(0,51,102));
        tb.setForeground(Color.white);
        tb.setFont(new Font("tahome", Font.PLAIN, 12));
        table_utilisateur.setBackground(Color.WHITE);
        table_utilisateur.setModel(tab_user);
        table_utilisateur.getColumnModel().getColumn(0).setPreferredWidth(250);
        table_utilisateur.getColumnModel().getColumn(0).setMaxWidth(250);
        table_utilisateur.getColumnModel().getColumn(0).setMinWidth(250);
      
        table_utilisateur.getColumnModel().getColumn(1).setPreferredWidth(135);
        table_utilisateur.getColumnModel().getColumn(1).setMaxWidth(135);
        table_utilisateur.getColumnModel().getColumn(1).setMinWidth(135);
      
        table_utilisateur.getColumnModel().getColumn(2).setPreferredWidth(100);
        table_utilisateur.getColumnModel().getColumn(2).setMaxWidth(100);
        table_utilisateur.getColumnModel().getColumn(2).setMinWidth(100);
    
   recuperer_val_utilisateur();
    }
public void recuperer_val_utilisateur() throws Exception{ 
        tab_user.setRowCount(0);//initialisation du table
        query = "select * from utilisateur";
        st = maCon.Obtenirconnexion().createStatement();
        ResultSet rs = st.executeQuery(query);
  while(rs.next()){
       user = rs.getString("nom_user");
       pwd = rs.getString("mot_de_passe_user");
      // String pws = " mot de passe";
       privillege= rs.getString("privilege");
       Object[] userobj = {user,pwd, privillege};
       tab_user.addRow(userobj);
       //txt_pwd_v.setEchoChar('*');
    }
    } 
    private void btn_auth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auth2ActionPerformed
        int index_p = table_utilisateur.getSelectedRow();
        TableModel mod_p = table_utilisateur.getModel();
        String user = mod_p.getValueAt(index_p, 0).toString();
        String pwd = mod_p.getValueAt(index_p, 1).toString();
        String privillege= mod_p.getValueAt(index_p, 2).toString();
        user_mod um = new user_mod();
        um.setVisible(true);
        um.pack();
        um.txt_user_mod.setText(user);
        um.txtx_ref_pwd.setText(pwd);
        um.txt_ref_user.setText(user);
//        um.txt_ref_privi.setText(privillege);
    }//GEN-LAST:event_btn_auth2ActionPerformed
  public void pdfUser(String nom, String Titre, int nb) throws FileNotFoundException, DocumentException, IOException{
       Document document = new Document(PageSize.A4);
       PdfWriter.getInstance(document, new FileOutputStream(nom));
       document.open();
       Date actuelle = new Date();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
            String date_now = dateFormat.format(actuelle);
            //creation d'une font
            com.itextpdf.text.Font fontGray = FontFactory.getFont("Arial", 6, BaseColor.GRAY);
            com.itextpdf.text.Font fontBlack = FontFactory.getFont("Arial", 7, BaseColor.BLACK);
            com.itextpdf.text.Font fontBlue = FontFactory.getFont("Verdana", 12, BaseColor.LIGHT_GRAY);
            com.itextpdf.text.Font blanc = FontFactory.getFont("Arial", 7, BaseColor.BLACK);

            document.add(new Paragraph("\n"));//saut de ligne
            Paragraph titre1 = new Paragraph("AUTO-TRACTOR FIANARANTSOA SARL", fontGray);
            titre1.setAlignment(1);
            document.add(titre1);
            document.add(new Phrase(Chunk.NEWLINE));
            document.add(new Phrase(Chunk.ALIGN_LEFT));
            document.add(new Phrase("AUTO-TRACTOR \nBP:1462 ZOROZOROANA-FIANARANTSOA\n FIANARANTSOA 301 \n Tél:020 75 509 01 - 034 75 509 01"));
            document.add(new Paragraph(date_now));
            document.add(new Phrase(Chunk.ALIGN_RIGHT));
            // document.add(new Paragraph("\n"));//saut de ligne
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            //document.add(new Paragraph("\n"));//saut de ligne
            Paragraph titre = new Paragraph(Titre.toUpperCase(), fontBlue);
            titre.setAlignment(1);
            document.add(titre);
            document.add(new Phrase(Chunk.NEWLINE));
            document.add(new Paragraph("\n"));//saut de ligne
            //table
            PdfPTable tablePdf = new PdfPTable(nb);
            
            tablePdf.setWidthPercentage(100);
            PdfPCell cel0 = new PdfPCell(new Paragraph("Utilisateur", FontFactory.getFont("Arial", 8, BaseColor.WHITE)));
            PdfPCell cel1 = new PdfPCell(new Paragraph("Mot de passe", FontFactory.getFont("Arial", 8, BaseColor.WHITE)));
            PdfPCell cel2 = new PdfPCell(new Paragraph("Privillège", FontFactory.getFont("Arial", 8, BaseColor.WHITE)));
           
            //PdfPCell cel7 = new PdfPCell(new Paragraph("Im",FontFactory.getFont("Arial", 7, BaseColor.BLACK)));
            // PdfPCell cel8 = new PdfPCell(new Paragraph("Im",FontFactory.getFont("Arial", 7, BaseColor.BLACK)));
            //ajout du table header
            //tableau Header
            tablePdf.addCell(cel0).setBackgroundColor(BaseColor.BLUE);
            tablePdf.addCell(cel1).setBackgroundColor(BaseColor.BLUE);
            tablePdf.addCell(cel2).setBackgroundColor(BaseColor.BLUE);
            //tablePdf.addCell(cel7);
            //PdfPCell colonne =new PdfPCell(); 
            //  colonne.setHorizontalAlignment(1);
            //colonne.setBackgroundColor(BaseColor.GRAY);
            // colonne.setBackgroundColor(BaseColor.GRAY);
            // tablePdf.addCell(colonne);
            Connexion connect = new Connexion();
            ResultSet rs = null;
            Connection con = connect.obtenirconnexion();
            try {
                Statement stat = con.createStatement();

                String sql = "";
                sql = "select * from utilisateur order by nom_user";
                rs = stat.executeQuery(sql);
                while (rs.next()) {
                    tablePdf.addCell(new Phrase(rs.getString(2), blanc));
                    tablePdf.addCell(new Phrase(rs.getString(3), blanc));
                    tablePdf.addCell(new Phrase(rs.getString(4), blanc));
                    //tablePdf.addCell(new Phrase(rs.getString(4), blanc));
                }
            } catch (SQLException e) {
            }
            document.add(tablePdf);
            document.close();
            //JOptionPane.showMessageDialog(null, "Exportation avec succes !");

            //ouverture du fichier PDF crée
            try {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler" + "C:\\Users\\VONIANAHITRA\\Documents\\NetBeansProjects\\Application\\utilisateur.pdf");
                Desktop.getDesktop().open(new File("C:\\Users\\VONIANAHITRA\\Documents\\NetBeansProjects\\Application\\utilisateur.pdf"));

            } catch (RuntimeException e) {
                // JOptionPane.showMessageDialog(null, "Impossible d'ouvrir le fichier! "+e);
            }  
  }
public String GetPrimaryKey(JTable tab){
        String val;
        int row = tab.getSelectedRow();
        //int col = table_user_list.getSelectedColumn();
        if(row == -1) 
        //JOptionPane.showMessageDialog(null,"Veillez selectionner un employe  ","Message",JOptionPane.WARNING_MESSAGE);    
            return null;  
            val = tab.getValueAt(row, 0).toString();
            return val;
    }
    private void btn_auth4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auth4ActionPerformed
        int index_sup_user = table_utilisateur.getSelectedRow();
        TableModel user_sup = table_utilisateur.getModel();
        String num = user_sup.getValueAt(index_sup_user, 0).toString();
        String pwd = user_sup.getValueAt(index_sup_user, 1).toString();
        String privi = user_sup.getValueAt(index_sup_user, 2).toString();
    if(num !=null && pwd !=null && privi !=null){
            try {
                //classe_user user = new classe_user();
                requet_user sup = new requet_user();
                sup.supprimer(num, pwd, privi);
    JOptionPane.showMessageDialog(null,"L'utilisateur a été bien supprimé.\n Veuillez verifier SVP!","Message",JOptionPane.PLAIN_MESSAGE);
    config_tab_perso();
            } catch (Exception ex) {
                Logger.getLogger(user_liste.class.getName()).log(Level.SEVERE, null, ex);
            }
    }else{
    JOptionPane.showMessageDialog(null,"Veillez sélectionné l'utilisateur que vous voulez supprimer.\nSVP!","Message",JOptionPane.PLAIN_MESSAGE);    
    }
    }//GEN-LAST:event_btn_auth4ActionPerformed

    private void btn_auth5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auth5ActionPerformed
     authentificaiton auth = new authentificaiton();
        auth.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_btn_auth5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_liste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_auth;
    private javax.swing.JButton btn_auth1;
    private javax.swing.JButton btn_auth2;
    private javax.swing.JButton btn_auth4;
    private javax.swing.JButton btn_auth5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_utilisateur;
    // End of variables declaration//GEN-END:variables
}
